/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * GraceOn Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  MemberLoginRequest,
  MemberSignupRequest,
  ResultDTOMemberAuthResponse,
  ResultDTOMemberInfo,
} from "../graceOnAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * 약관 동의 후 회원을 생성하고 회원 토큰을 발급한다(가입 즉시 로그인). 과도한 요청은 차단.
 * @summary 회원가입
 */
export const memberAuthSignupCreate = (
  memberSignupRequest: MemberSignupRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOMemberAuthResponse>({
    url: `/pub/v1/auth/signup`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: memberSignupRequest,
    signal,
  });
};

export const getMemberAuthSignupCreateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof memberAuthSignupCreate>>,
    TError,
    { data: MemberSignupRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof memberAuthSignupCreate>>,
  TError,
  { data: MemberSignupRequest },
  TContext
> => {
  const mutationKey = ["memberAuthSignupCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof memberAuthSignupCreate>>,
    { data: MemberSignupRequest }
  > = (props) => {
    const { data } = props ?? {};

    return memberAuthSignupCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type MemberAuthSignupCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof memberAuthSignupCreate>>
>;
export type MemberAuthSignupCreateMutationBody = MemberSignupRequest;
export type MemberAuthSignupCreateMutationError = unknown;

/**
 * @summary 회원가입
 */
export const useMemberAuthSignupCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof memberAuthSignupCreate>>,
      TError,
      { data: MemberSignupRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof memberAuthSignupCreate>>,
  TError,
  { data: MemberSignupRequest },
  TContext
> => {
  const mutationOptions = getMemberAuthSignupCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 이메일/비밀번호로 로그인하고 회원 토큰을 발급한다. 과도한 요청은 차단.
 * @summary 회원 로그인
 */
export const memberAuthLogin = (
  memberLoginRequest: MemberLoginRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOMemberAuthResponse>({
    url: `/pub/v1/auth/login`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: memberLoginRequest,
    signal,
  });
};

export const getMemberAuthLoginMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof memberAuthLogin>>,
    TError,
    { data: MemberLoginRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof memberAuthLogin>>,
  TError,
  { data: MemberLoginRequest },
  TContext
> => {
  const mutationKey = ["memberAuthLogin"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof memberAuthLogin>>,
    { data: MemberLoginRequest }
  > = (props) => {
    const { data } = props ?? {};

    return memberAuthLogin(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type MemberAuthLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof memberAuthLogin>>
>;
export type MemberAuthLoginMutationBody = MemberLoginRequest;
export type MemberAuthLoginMutationError = unknown;

/**
 * @summary 회원 로그인
 */
export const useMemberAuthLogin = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof memberAuthLogin>>,
      TError,
      { data: MemberLoginRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof memberAuthLogin>>,
  TError,
  { data: MemberLoginRequest },
  TContext
> => {
  const mutationOptions = getMemberAuthLoginMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 회원 토큰으로 로그인한 회원의 프로필을 반환한다.
 * @summary 내 정보
 */
export const memberAuthMe = (signal?: AbortSignal) => {
  return customInstance<ResultDTOMemberInfo>({
    url: `/pub/v1/auth/me`,
    method: "GET",
    signal,
  });
};

export const getMemberAuthMeQueryKey = () => {
  return [`/pub/v1/auth/me`] as const;
};

export const getMemberAuthMeQueryOptions = <
  TData = Awaited<ReturnType<typeof memberAuthMe>>,
  TError = unknown
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof memberAuthMe>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getMemberAuthMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof memberAuthMe>>> = ({
    signal,
  }) => memberAuthMe(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof memberAuthMe>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type MemberAuthMeQueryResult = NonNullable<
  Awaited<ReturnType<typeof memberAuthMe>>
>;
export type MemberAuthMeQueryError = unknown;

export function useMemberAuthMe<
  TData = Awaited<ReturnType<typeof memberAuthMe>>,
  TError = unknown
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof memberAuthMe>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof memberAuthMe>>,
          TError,
          Awaited<ReturnType<typeof memberAuthMe>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMemberAuthMe<
  TData = Awaited<ReturnType<typeof memberAuthMe>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof memberAuthMe>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof memberAuthMe>>,
          TError,
          Awaited<ReturnType<typeof memberAuthMe>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMemberAuthMe<
  TData = Awaited<ReturnType<typeof memberAuthMe>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof memberAuthMe>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 내 정보
 */

export function useMemberAuthMe<
  TData = Awaited<ReturnType<typeof memberAuthMe>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof memberAuthMe>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getMemberAuthMeQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
