/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * GraceOn Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CampaignDto,
  CampaignSearchRequest,
  CampaignStatusChangeRequest,
  ResultDTOCampaignDto,
  ResultDTOListCampaignDto,
  ResultDTOVoid,
} from "../graceOnAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * @summary 캠페인 상세
 */
export const campaignDetail = (id: number, signal?: AbortSignal) => {
  return customInstance<ResultDTOCampaignDto>({
    url: `/v1/campaign/${id}`,
    method: "GET",
    signal,
  });
};

export const getCampaignDetailQueryKey = (id?: number) => {
  return [`/v1/campaign/${id}`] as const;
};

export const getCampaignDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof campaignDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof campaignDetail>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getCampaignDetailQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof campaignDetail>>> = ({
    signal,
  }) => campaignDetail(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof campaignDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CampaignDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof campaignDetail>>
>;
export type CampaignDetailQueryError = unknown;

export function useCampaignDetail<
  TData = Awaited<ReturnType<typeof campaignDetail>>,
  TError = unknown
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof campaignDetail>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof campaignDetail>>,
          TError,
          Awaited<ReturnType<typeof campaignDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCampaignDetail<
  TData = Awaited<ReturnType<typeof campaignDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof campaignDetail>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof campaignDetail>>,
          TError,
          Awaited<ReturnType<typeof campaignDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCampaignDetail<
  TData = Awaited<ReturnType<typeof campaignDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof campaignDetail>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 캠페인 상세
 */

export function useCampaignDetail<
  TData = Awaited<ReturnType<typeof campaignDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof campaignDetail>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getCampaignDetailQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 캠페인 수정
 */
export const campaignUpdate = (id: number, campaignDto: CampaignDto) => {
  return customInstance<ResultDTOCampaignDto>({
    url: `/v1/campaign/${id}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: campaignDto,
  });
};

export const getCampaignUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof campaignUpdate>>,
    TError,
    { id: number; data: CampaignDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof campaignUpdate>>,
  TError,
  { id: number; data: CampaignDto },
  TContext
> => {
  const mutationKey = ["campaignUpdate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof campaignUpdate>>,
    { id: number; data: CampaignDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return campaignUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CampaignUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof campaignUpdate>>
>;
export type CampaignUpdateMutationBody = CampaignDto;
export type CampaignUpdateMutationError = unknown;

/**
 * @summary 캠페인 수정
 */
export const useCampaignUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof campaignUpdate>>,
      TError,
      { id: number; data: CampaignDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof campaignUpdate>>,
  TError,
  { id: number; data: CampaignDto },
  TContext
> => {
  const mutationOptions = getCampaignUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 캠페인 삭제
 */
export const campaignDelete = (id: number) => {
  return customInstance<ResultDTOVoid>({
    url: `/v1/campaign/${id}`,
    method: "DELETE",
  });
};

export const getCampaignDeleteMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof campaignDelete>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof campaignDelete>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["campaignDelete"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof campaignDelete>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return campaignDelete(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type CampaignDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof campaignDelete>>
>;

export type CampaignDeleteMutationError = unknown;

/**
 * @summary 캠페인 삭제
 */
export const useCampaignDelete = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof campaignDelete>>,
      TError,
      { id: number },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof campaignDelete>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getCampaignDeleteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 캠페인 상태 변경
 */
export const campaignStatus = (
  id: number,
  campaignStatusChangeRequest: CampaignStatusChangeRequest
) => {
  return customInstance<ResultDTOCampaignDto>({
    url: `/v1/campaign/${id}/status`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: campaignStatusChangeRequest,
  });
};

export const getCampaignStatusMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof campaignStatus>>,
    TError,
    { id: number; data: CampaignStatusChangeRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof campaignStatus>>,
  TError,
  { id: number; data: CampaignStatusChangeRequest },
  TContext
> => {
  const mutationKey = ["campaignStatus"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof campaignStatus>>,
    { id: number; data: CampaignStatusChangeRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return campaignStatus(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CampaignStatusMutationResult = NonNullable<
  Awaited<ReturnType<typeof campaignStatus>>
>;
export type CampaignStatusMutationBody = CampaignStatusChangeRequest;
export type CampaignStatusMutationError = unknown;

/**
 * @summary 캠페인 상태 변경
 */
export const useCampaignStatus = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof campaignStatus>>,
      TError,
      { id: number; data: CampaignStatusChangeRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof campaignStatus>>,
  TError,
  { id: number; data: CampaignStatusChangeRequest },
  TContext
> => {
  const mutationOptions = getCampaignStatusMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 캠페인 등록
 */
export const campaignCreate = (
  campaignDto: CampaignDto,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOCampaignDto>({
    url: `/v1/campaign`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: campaignDto,
    signal,
  });
};

export const getCampaignCreateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof campaignCreate>>,
    TError,
    { data: CampaignDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof campaignCreate>>,
  TError,
  { data: CampaignDto },
  TContext
> => {
  const mutationKey = ["campaignCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof campaignCreate>>,
    { data: CampaignDto }
  > = (props) => {
    const { data } = props ?? {};

    return campaignCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CampaignCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof campaignCreate>>
>;
export type CampaignCreateMutationBody = CampaignDto;
export type CampaignCreateMutationError = unknown;

/**
 * @summary 캠페인 등록
 */
export const useCampaignCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof campaignCreate>>,
      TError,
      { data: CampaignDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof campaignCreate>>,
  TError,
  { data: CampaignDto },
  TContext
> => {
  const mutationOptions = getCampaignCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 관리자용 전체 캠페인 목록(최신순). 유형/상태로 필터링.
 * @summary 캠페인 목록
 */
export const campaignList = (
  campaignSearchRequest: CampaignSearchRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOListCampaignDto>({
    url: `/v1/campaign/list`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: campaignSearchRequest,
    signal,
  });
};

export const getCampaignListMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof campaignList>>,
    TError,
    { data: CampaignSearchRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof campaignList>>,
  TError,
  { data: CampaignSearchRequest },
  TContext
> => {
  const mutationKey = ["campaignList"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof campaignList>>,
    { data: CampaignSearchRequest }
  > = (props) => {
    const { data } = props ?? {};

    return campaignList(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CampaignListMutationResult = NonNullable<
  Awaited<ReturnType<typeof campaignList>>
>;
export type CampaignListMutationBody = CampaignSearchRequest;
export type CampaignListMutationError = unknown;

/**
 * @summary 캠페인 목록
 */
export const useCampaignList = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof campaignList>>,
      TError,
      { data: CampaignSearchRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof campaignList>>,
  TError,
  { data: CampaignSearchRequest },
  TContext
> => {
  const mutationOptions = getCampaignListMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
