/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * StreamHub Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CouponDto,
  CouponSearchRequest,
  ResultDTOCouponDto,
  ResultDTOListCouponDto,
  ResultDTOVoid,
} from "../streamHubAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * @summary 쿠폰 상세
 */
export const couponDetail = (id: number, signal?: AbortSignal) => {
  return customInstance<ResultDTOCouponDto>({
    url: `/v1/coupon/${id}`,
    method: "GET",
    signal,
  });
};

export const getCouponDetailQueryKey = (id?: number) => {
  return [`/v1/coupon/${id}`] as const;
};

export const getCouponDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof couponDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof couponDetail>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getCouponDetailQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof couponDetail>>> = ({
    signal,
  }) => couponDetail(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof couponDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CouponDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof couponDetail>>
>;
export type CouponDetailQueryError = unknown;

export function useCouponDetail<
  TData = Awaited<ReturnType<typeof couponDetail>>,
  TError = unknown
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof couponDetail>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof couponDetail>>,
          TError,
          Awaited<ReturnType<typeof couponDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCouponDetail<
  TData = Awaited<ReturnType<typeof couponDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof couponDetail>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof couponDetail>>,
          TError,
          Awaited<ReturnType<typeof couponDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCouponDetail<
  TData = Awaited<ReturnType<typeof couponDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof couponDetail>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 쿠폰 상세
 */

export function useCouponDetail<
  TData = Awaited<ReturnType<typeof couponDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof couponDetail>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getCouponDetailQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 쿠폰 수정
 */
export const couponUpdate = (id: number, couponDto: CouponDto) => {
  return customInstance<ResultDTOCouponDto>({
    url: `/v1/coupon/${id}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: couponDto,
  });
};

export const getCouponUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof couponUpdate>>,
    TError,
    { id: number; data: CouponDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof couponUpdate>>,
  TError,
  { id: number; data: CouponDto },
  TContext
> => {
  const mutationKey = ["couponUpdate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof couponUpdate>>,
    { id: number; data: CouponDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return couponUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CouponUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof couponUpdate>>
>;
export type CouponUpdateMutationBody = CouponDto;
export type CouponUpdateMutationError = unknown;

/**
 * @summary 쿠폰 수정
 */
export const useCouponUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof couponUpdate>>,
      TError,
      { id: number; data: CouponDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof couponUpdate>>,
  TError,
  { id: number; data: CouponDto },
  TContext
> => {
  const mutationOptions = getCouponUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 쿠폰 삭제
 */
export const couponDelete = (id: number) => {
  return customInstance<ResultDTOVoid>({
    url: `/v1/coupon/${id}`,
    method: "DELETE",
  });
};

export const getCouponDeleteMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof couponDelete>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof couponDelete>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["couponDelete"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof couponDelete>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return couponDelete(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type CouponDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof couponDelete>>
>;

export type CouponDeleteMutationError = unknown;

/**
 * @summary 쿠폰 삭제
 */
export const useCouponDelete = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof couponDelete>>,
      TError,
      { id: number },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof couponDelete>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getCouponDeleteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 쿠폰 등록
 */
export const couponCreate = (couponDto: CouponDto, signal?: AbortSignal) => {
  return customInstance<ResultDTOCouponDto>({
    url: `/v1/coupon`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: couponDto,
    signal,
  });
};

export const getCouponCreateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof couponCreate>>,
    TError,
    { data: CouponDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof couponCreate>>,
  TError,
  { data: CouponDto },
  TContext
> => {
  const mutationKey = ["couponCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof couponCreate>>,
    { data: CouponDto }
  > = (props) => {
    const { data } = props ?? {};

    return couponCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CouponCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof couponCreate>>
>;
export type CouponCreateMutationBody = CouponDto;
export type CouponCreateMutationError = unknown;

/**
 * @summary 쿠폰 등록
 */
export const useCouponCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof couponCreate>>,
      TError,
      { data: CouponDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof couponCreate>>,
  TError,
  { data: CouponDto },
  TContext
> => {
  const mutationOptions = getCouponCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 관리자용 쿠폰 목록(최신순). 사용여부/키워드 필터 가능.
 * @summary 쿠폰 목록
 */
export const couponList = (
  couponSearchRequest: CouponSearchRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOListCouponDto>({
    url: `/v1/coupon/list`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: couponSearchRequest,
    signal,
  });
};

export const getCouponListMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof couponList>>,
    TError,
    { data: CouponSearchRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof couponList>>,
  TError,
  { data: CouponSearchRequest },
  TContext
> => {
  const mutationKey = ["couponList"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof couponList>>,
    { data: CouponSearchRequest }
  > = (props) => {
    const { data } = props ?? {};

    return couponList(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CouponListMutationResult = NonNullable<
  Awaited<ReturnType<typeof couponList>>
>;
export type CouponListMutationBody = CouponSearchRequest;
export type CouponListMutationError = unknown;

/**
 * @summary 쿠폰 목록
 */
export const useCouponList = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof couponList>>,
      TError,
      { data: CouponSearchRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof couponList>>,
  TError,
  { data: CouponSearchRequest },
  TContext
> => {
  const mutationOptions = getCouponListMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
