/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * StreamHub Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  MemberOrderCreateRequest,
  ResultDTOListMemberOrderListItem,
  ResultDTOMemberOrderResult,
} from "../streamHubAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * 로그인 회원의 주문 목록을 최신순으로 반환한다.
 * @summary 구매내역
 */
export const memberOrderOrders = (signal?: AbortSignal) => {
  return customInstance<ResultDTOListMemberOrderListItem>({
    url: `/pub/v1/orders`,
    method: "GET",
    signal,
  });
};

export const getMemberOrderOrdersQueryKey = () => {
  return [`/pub/v1/orders`] as const;
};

export const getMemberOrderOrdersQueryOptions = <
  TData = Awaited<ReturnType<typeof memberOrderOrders>>,
  TError = unknown
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof memberOrderOrders>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getMemberOrderOrdersQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof memberOrderOrders>>
  > = ({ signal }) => memberOrderOrders(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof memberOrderOrders>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type MemberOrderOrdersQueryResult = NonNullable<
  Awaited<ReturnType<typeof memberOrderOrders>>
>;
export type MemberOrderOrdersQueryError = unknown;

export function useMemberOrderOrders<
  TData = Awaited<ReturnType<typeof memberOrderOrders>>,
  TError = unknown
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof memberOrderOrders>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof memberOrderOrders>>,
          TError,
          Awaited<ReturnType<typeof memberOrderOrders>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMemberOrderOrders<
  TData = Awaited<ReturnType<typeof memberOrderOrders>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof memberOrderOrders>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof memberOrderOrders>>,
          TError,
          Awaited<ReturnType<typeof memberOrderOrders>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMemberOrderOrders<
  TData = Awaited<ReturnType<typeof memberOrderOrders>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof memberOrderOrders>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 구매내역
 */

export function useMemberOrderOrders<
  TData = Awaited<ReturnType<typeof memberOrderOrders>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof memberOrderOrders>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getMemberOrderOrdersQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 로그인 회원이 앨범을 구매하면 주문이 생성되고 (가짜) 결제로 PAID 처리된다.
 * @summary 음반 구매
 */
export const memberOrderOrdersCreate = (
  memberOrderCreateRequest: MemberOrderCreateRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOMemberOrderResult>({
    url: `/pub/v1/orders`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: memberOrderCreateRequest,
    signal,
  });
};

export const getMemberOrderOrdersCreateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof memberOrderOrdersCreate>>,
    TError,
    { data: MemberOrderCreateRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof memberOrderOrdersCreate>>,
  TError,
  { data: MemberOrderCreateRequest },
  TContext
> => {
  const mutationKey = ["memberOrderOrdersCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof memberOrderOrdersCreate>>,
    { data: MemberOrderCreateRequest }
  > = (props) => {
    const { data } = props ?? {};

    return memberOrderOrdersCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type MemberOrderOrdersCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof memberOrderOrdersCreate>>
>;
export type MemberOrderOrdersCreateMutationBody = MemberOrderCreateRequest;
export type MemberOrderOrdersCreateMutationError = unknown;

/**
 * @summary 음반 구매
 */
export const useMemberOrderOrdersCreate = <
  TError = unknown,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof memberOrderOrdersCreate>>,
      TError,
      { data: MemberOrderCreateRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof memberOrderOrdersCreate>>,
  TError,
  { data: MemberOrderCreateRequest },
  TContext
> => {
  const mutationOptions = getMemberOrderOrdersCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
