/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * StreamHub Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type {
  GoodsStockSearchRequest,
  GoodsStockUpdateRequest,
  ResultDTOGoodsStockDto,
  ResultDTOListGoodsStockDto,
} from "../streamHubAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * 재고수량(및 선택적으로 알림기준수량)을 수정한다.
 * @summary 재고 수정
 */
export const goodsStockStockUpdate = (
  id: number,
  goodsStockUpdateRequest: GoodsStockUpdateRequest
) => {
  return customInstance<ResultDTOGoodsStockDto>({
    url: `/v1/goods-stock/${id}/stock`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: goodsStockUpdateRequest,
  });
};

export const getGoodsStockStockUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof goodsStockStockUpdate>>,
    TError,
    { id: number; data: GoodsStockUpdateRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof goodsStockStockUpdate>>,
  TError,
  { id: number; data: GoodsStockUpdateRequest },
  TContext
> => {
  const mutationKey = ["goodsStockStockUpdate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof goodsStockStockUpdate>>,
    { id: number; data: GoodsStockUpdateRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return goodsStockStockUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type GoodsStockStockUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof goodsStockStockUpdate>>
>;
export type GoodsStockStockUpdateMutationBody = GoodsStockUpdateRequest;
export type GoodsStockStockUpdateMutationError = unknown;

/**
 * @summary 재고 수정
 */
export const useGoodsStockStockUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof goodsStockStockUpdate>>,
      TError,
      { id: number; data: GoodsStockUpdateRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof goodsStockStockUpdate>>,
  TError,
  { id: number; data: GoodsStockUpdateRequest },
  TContext
> => {
  const mutationOptions = getGoodsStockStockUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 품절 여부(Y/N)를 전환한다.
 * @summary 품절 토글
 */
export const goodsStockSoldoutUpdate = (id: number) => {
  return customInstance<ResultDTOGoodsStockDto>({
    url: `/v1/goods-stock/${id}/soldout`,
    method: "PUT",
  });
};

export const getGoodsStockSoldoutUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof goodsStockSoldoutUpdate>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof goodsStockSoldoutUpdate>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["goodsStockSoldoutUpdate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof goodsStockSoldoutUpdate>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return goodsStockSoldoutUpdate(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type GoodsStockSoldoutUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof goodsStockSoldoutUpdate>>
>;

export type GoodsStockSoldoutUpdateMutationError = unknown;

/**
 * @summary 품절 토글
 */
export const useGoodsStockSoldoutUpdate = <
  TError = unknown,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof goodsStockSoldoutUpdate>>,
      TError,
      { id: number },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof goodsStockSoldoutUpdate>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getGoodsStockSoldoutUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 키워드/재고부족 필터 및 재고 오름차순 정렬을 지원하는 재고 목록.
 * @summary 재고 목록
 */
export const goodsStockList = (
  goodsStockSearchRequest: GoodsStockSearchRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOListGoodsStockDto>({
    url: `/v1/goods-stock/list`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: goodsStockSearchRequest,
    signal,
  });
};

export const getGoodsStockListMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof goodsStockList>>,
    TError,
    { data: GoodsStockSearchRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof goodsStockList>>,
  TError,
  { data: GoodsStockSearchRequest },
  TContext
> => {
  const mutationKey = ["goodsStockList"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof goodsStockList>>,
    { data: GoodsStockSearchRequest }
  > = (props) => {
    const { data } = props ?? {};

    return goodsStockList(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type GoodsStockListMutationResult = NonNullable<
  Awaited<ReturnType<typeof goodsStockList>>
>;
export type GoodsStockListMutationBody = GoodsStockSearchRequest;
export type GoodsStockListMutationError = unknown;

/**
 * @summary 재고 목록
 */
export const useGoodsStockList = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof goodsStockList>>,
      TError,
      { data: GoodsStockSearchRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof goodsStockList>>,
  TError,
  { data: GoodsStockSearchRequest },
  TContext
> => {
  const mutationOptions = getGoodsStockListMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
