/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * GraceOn Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type {
  BoardDto,
  ResultDTOBoardDto,
  ResultDTOListBoardDto,
  ResultDTOVoid,
} from "../graceOnAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * @summary 게시판 수정
 */
export const boardUpdate = (id: number, boardDto: BoardDto) => {
  return customInstance<ResultDTOBoardDto>({
    url: `/v1/board/${id}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: boardDto,
  });
};

export const getBoardUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof boardUpdate>>,
    TError,
    { id: number; data: BoardDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof boardUpdate>>,
  TError,
  { id: number; data: BoardDto },
  TContext
> => {
  const mutationKey = ["boardUpdate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof boardUpdate>>,
    { id: number; data: BoardDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return boardUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type BoardUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof boardUpdate>>
>;
export type BoardUpdateMutationBody = BoardDto;
export type BoardUpdateMutationError = unknown;

/**
 * @summary 게시판 수정
 */
export const useBoardUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof boardUpdate>>,
      TError,
      { id: number; data: BoardDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof boardUpdate>>,
  TError,
  { id: number; data: BoardDto },
  TContext
> => {
  const mutationOptions = getBoardUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 게시판 삭제
 */
export const boardDelete = (id: number) => {
  return customInstance<ResultDTOVoid>({
    url: `/v1/board/${id}`,
    method: "DELETE",
  });
};

export const getBoardDeleteMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof boardDelete>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof boardDelete>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["boardDelete"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof boardDelete>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return boardDelete(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type BoardDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof boardDelete>>
>;

export type BoardDeleteMutationError = unknown;

/**
 * @summary 게시판 삭제
 */
export const useBoardDelete = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof boardDelete>>,
      TError,
      { id: number },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof boardDelete>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getBoardDeleteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 게시판 등록
 */
export const boardCreate = (boardDto: BoardDto, signal?: AbortSignal) => {
  return customInstance<ResultDTOBoardDto>({
    url: `/v1/board`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: boardDto,
    signal,
  });
};

export const getBoardCreateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof boardCreate>>,
    TError,
    { data: BoardDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof boardCreate>>,
  TError,
  { data: BoardDto },
  TContext
> => {
  const mutationKey = ["boardCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof boardCreate>>,
    { data: BoardDto }
  > = (props) => {
    const { data } = props ?? {};

    return boardCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type BoardCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof boardCreate>>
>;
export type BoardCreateMutationBody = BoardDto;
export type BoardCreateMutationError = unknown;

/**
 * @summary 게시판 등록
 */
export const useBoardCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof boardCreate>>,
      TError,
      { data: BoardDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof boardCreate>>,
  TError,
  { data: BoardDto },
  TContext
> => {
  const mutationOptions = getBoardCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 관리자용 전체 게시판 목록(정렬순).
 * @summary 게시판 목록
 */
export const boardList = (signal?: AbortSignal) => {
  return customInstance<ResultDTOListBoardDto>({
    url: `/v1/board/list`,
    method: "POST",
    signal,
  });
};

export const getBoardListMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof boardList>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof boardList>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["boardList"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof boardList>>,
    void
  > = () => {
    return boardList();
  };

  return { mutationFn, ...mutationOptions };
};

export type BoardListMutationResult = NonNullable<
  Awaited<ReturnType<typeof boardList>>
>;

export type BoardListMutationError = unknown;

/**
 * @summary 게시판 목록
 */
export const useBoardList = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof boardList>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof boardList>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getBoardListMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
