/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * GraceOn Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  GoodsInquiryAnswerRequest,
  GoodsInquirySearchRequest,
  ResultDTOGoodsInquiryDto,
  ResultDTOListGoodsInquiryDto,
  ResultDTOVoid,
} from "../graceOnAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * @summary 상품문의 답변 등록
 */
export const goodsInquiryAnswerUpdate = (
  id: number,
  goodsInquiryAnswerRequest: GoodsInquiryAnswerRequest
) => {
  return customInstance<ResultDTOGoodsInquiryDto>({
    url: `/v1/goods-inquiry/${id}/answer`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: goodsInquiryAnswerRequest,
  });
};

export const getGoodsInquiryAnswerUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof goodsInquiryAnswerUpdate>>,
    TError,
    { id: number; data: GoodsInquiryAnswerRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof goodsInquiryAnswerUpdate>>,
  TError,
  { id: number; data: GoodsInquiryAnswerRequest },
  TContext
> => {
  const mutationKey = ["goodsInquiryAnswerUpdate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof goodsInquiryAnswerUpdate>>,
    { id: number; data: GoodsInquiryAnswerRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return goodsInquiryAnswerUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type GoodsInquiryAnswerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof goodsInquiryAnswerUpdate>>
>;
export type GoodsInquiryAnswerUpdateMutationBody = GoodsInquiryAnswerRequest;
export type GoodsInquiryAnswerUpdateMutationError = unknown;

/**
 * @summary 상품문의 답변 등록
 */
export const useGoodsInquiryAnswerUpdate = <
  TError = unknown,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof goodsInquiryAnswerUpdate>>,
      TError,
      { id: number; data: GoodsInquiryAnswerRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof goodsInquiryAnswerUpdate>>,
  TError,
  { id: number; data: GoodsInquiryAnswerRequest },
  TContext
> => {
  const mutationOptions = getGoodsInquiryAnswerUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 관리자용 상품문의 목록(최신순, 답변상태 선택 필터).
 * @summary 상품문의 목록
 */
export const goodsInquiryList = (
  goodsInquirySearchRequest: GoodsInquirySearchRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOListGoodsInquiryDto>({
    url: `/v1/goods-inquiry/list`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: goodsInquirySearchRequest,
    signal,
  });
};

export const getGoodsInquiryListMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof goodsInquiryList>>,
    TError,
    { data: GoodsInquirySearchRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof goodsInquiryList>>,
  TError,
  { data: GoodsInquirySearchRequest },
  TContext
> => {
  const mutationKey = ["goodsInquiryList"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof goodsInquiryList>>,
    { data: GoodsInquirySearchRequest }
  > = (props) => {
    const { data } = props ?? {};

    return goodsInquiryList(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type GoodsInquiryListMutationResult = NonNullable<
  Awaited<ReturnType<typeof goodsInquiryList>>
>;
export type GoodsInquiryListMutationBody = GoodsInquirySearchRequest;
export type GoodsInquiryListMutationError = unknown;

/**
 * @summary 상품문의 목록
 */
export const useGoodsInquiryList = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof goodsInquiryList>>,
      TError,
      { data: GoodsInquirySearchRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof goodsInquiryList>>,
  TError,
  { data: GoodsInquirySearchRequest },
  TContext
> => {
  const mutationOptions = getGoodsInquiryListMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 상품문의 상세
 */
export const goodsInquiryDetail = (id: number, signal?: AbortSignal) => {
  return customInstance<ResultDTOGoodsInquiryDto>({
    url: `/v1/goods-inquiry/${id}`,
    method: "GET",
    signal,
  });
};

export const getGoodsInquiryDetailQueryKey = (id?: number) => {
  return [`/v1/goods-inquiry/${id}`] as const;
};

export const getGoodsInquiryDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof goodsInquiryDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof goodsInquiryDetail>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGoodsInquiryDetailQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof goodsInquiryDetail>>
  > = ({ signal }) => goodsInquiryDetail(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof goodsInquiryDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GoodsInquiryDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof goodsInquiryDetail>>
>;
export type GoodsInquiryDetailQueryError = unknown;

export function useGoodsInquiryDetail<
  TData = Awaited<ReturnType<typeof goodsInquiryDetail>>,
  TError = unknown
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof goodsInquiryDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof goodsInquiryDetail>>,
          TError,
          Awaited<ReturnType<typeof goodsInquiryDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGoodsInquiryDetail<
  TData = Awaited<ReturnType<typeof goodsInquiryDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof goodsInquiryDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof goodsInquiryDetail>>,
          TError,
          Awaited<ReturnType<typeof goodsInquiryDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGoodsInquiryDetail<
  TData = Awaited<ReturnType<typeof goodsInquiryDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof goodsInquiryDetail>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 상품문의 상세
 */

export function useGoodsInquiryDetail<
  TData = Awaited<ReturnType<typeof goodsInquiryDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof goodsInquiryDetail>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGoodsInquiryDetailQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 상품문의 삭제
 */
export const goodsInquiryDelete = (id: number) => {
  return customInstance<ResultDTOVoid>({
    url: `/v1/goods-inquiry/${id}`,
    method: "DELETE",
  });
};

export const getGoodsInquiryDeleteMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof goodsInquiryDelete>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof goodsInquiryDelete>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["goodsInquiryDelete"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof goodsInquiryDelete>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return goodsInquiryDelete(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type GoodsInquiryDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof goodsInquiryDelete>>
>;

export type GoodsInquiryDeleteMutationError = unknown;

/**
 * @summary 상품문의 삭제
 */
export const useGoodsInquiryDelete = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof goodsInquiryDelete>>,
      TError,
      { id: number },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof goodsInquiryDelete>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getGoodsInquiryDeleteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
