/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * GraceOn Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type {
  ActionLogCursorRequest,
  ActionLogSearchRequest,
  ResultDTOResCursorListActionLogItem,
  ResultDTOResInfinityListActionLogItem,
} from "../graceOnAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * 관리자 액션 기록을 검색/페이지네이션 조회한다.
 * @summary 감사 로그 목록
 */
export const actionLogList = (
  actionLogSearchRequest: ActionLogSearchRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOResInfinityListActionLogItem>({
    url: `/v1/action-log/list`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: actionLogSearchRequest,
    signal,
  });
};

export const getActionLogListMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof actionLogList>>,
    TError,
    { data: ActionLogSearchRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof actionLogList>>,
  TError,
  { data: ActionLogSearchRequest },
  TContext
> => {
  const mutationKey = ["actionLogList"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof actionLogList>>,
    { data: ActionLogSearchRequest }
  > = (props) => {
    const { data } = props ?? {};

    return actionLogList(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ActionLogListMutationResult = NonNullable<
  Awaited<ReturnType<typeof actionLogList>>
>;
export type ActionLogListMutationBody = ActionLogSearchRequest;
export type ActionLogListMutationError = unknown;

/**
 * @summary 감사 로그 목록
 */
export const useActionLogList = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof actionLogList>>,
      TError,
      { data: ActionLogSearchRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof actionLogList>>,
  TError,
  { data: ActionLogSearchRequest },
  TContext
> => {
  const mutationOptions = getActionLogListMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 커서(keyset) 기반 조회. 깊은 페이지에서도 일정한 응답 시간이며, 조회 중 새 로그가 쌓여도 행이 중복되지 않는다.
 * @summary 감사 로그 커서 목록
 */
export const actionLogCursorCreate = (
  actionLogCursorRequest: ActionLogCursorRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOResCursorListActionLogItem>({
    url: `/v1/action-log/cursor`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: actionLogCursorRequest,
    signal,
  });
};

export const getActionLogCursorCreateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof actionLogCursorCreate>>,
    TError,
    { data: ActionLogCursorRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof actionLogCursorCreate>>,
  TError,
  { data: ActionLogCursorRequest },
  TContext
> => {
  const mutationKey = ["actionLogCursorCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof actionLogCursorCreate>>,
    { data: ActionLogCursorRequest }
  > = (props) => {
    const { data } = props ?? {};

    return actionLogCursorCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ActionLogCursorCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof actionLogCursorCreate>>
>;
export type ActionLogCursorCreateMutationBody = ActionLogCursorRequest;
export type ActionLogCursorCreateMutationError = unknown;

/**
 * @summary 감사 로그 커서 목록
 */
export const useActionLogCursorCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof actionLogCursorCreate>>,
      TError,
      { data: ActionLogCursorRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof actionLogCursorCreate>>,
  TError,
  { data: ActionLogCursorRequest },
  TContext
> => {
  const mutationOptions = getActionLogCursorCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
