/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * GraceOn Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ResultDTOListDailyCountDto,
  ResultDTOListVisitLogDto,
  ResultDTOVisitSummaryDto,
  VisitSearchRequest,
} from "../graceOnAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * 기간/디바이스/검색어 필터로 접속 로그를 최신순(최대 500건)으로 조회합니다.
 * @summary 접속 로그 목록
 */
export const visitList = (
  visitSearchRequest: VisitSearchRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOListVisitLogDto>({
    url: `/v1/visit/list`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: visitSearchRequest,
    signal,
  });
};

export const getVisitListMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof visitList>>,
    TError,
    { data: VisitSearchRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof visitList>>,
  TError,
  { data: VisitSearchRequest },
  TContext
> => {
  const mutationKey = ["visitList"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof visitList>>,
    { data: VisitSearchRequest }
  > = (props) => {
    const { data } = props ?? {};

    return visitList(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type VisitListMutationResult = NonNullable<
  Awaited<ReturnType<typeof visitList>>
>;
export type VisitListMutationBody = VisitSearchRequest;
export type VisitListMutationError = unknown;

/**
 * @summary 접속 로그 목록
 */
export const useVisitList = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof visitList>>,
      TError,
      { data: VisitSearchRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof visitList>>,
  TError,
  { data: VisitSearchRequest },
  TContext
> => {
  const mutationOptions = getVisitListMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 요청 기간의 일자별 접속 수를 반환합니다(기본 최근 30일, 빈 날짜는 0으로 채움).
 * @summary 일자별 접속 통계
 */
export const visitDailyCreate = (
  visitSearchRequest: VisitSearchRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOListDailyCountDto>({
    url: `/v1/visit/daily`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: visitSearchRequest,
    signal,
  });
};

export const getVisitDailyCreateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof visitDailyCreate>>,
    TError,
    { data: VisitSearchRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof visitDailyCreate>>,
  TError,
  { data: VisitSearchRequest },
  TContext
> => {
  const mutationKey = ["visitDailyCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof visitDailyCreate>>,
    { data: VisitSearchRequest }
  > = (props) => {
    const { data } = props ?? {};

    return visitDailyCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type VisitDailyCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof visitDailyCreate>>
>;
export type VisitDailyCreateMutationBody = VisitSearchRequest;
export type VisitDailyCreateMutationError = unknown;

/**
 * @summary 일자별 접속 통계
 */
export const useVisitDailyCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof visitDailyCreate>>,
      TError,
      { data: VisitSearchRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof visitDailyCreate>>,
  TError,
  { data: VisitSearchRequest },
  TContext
> => {
  const mutationOptions = getVisitDailyCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 총 접속 수, 오늘 접속 수, 추정 순방문자 수, 상위 경로 5개, 디바이스별 분포를 반환합니다.
 * @summary 접속 통계 요약
 */
export const visitSummary = (signal?: AbortSignal) => {
  return customInstance<ResultDTOVisitSummaryDto>({
    url: `/v1/visit/summary`,
    method: "GET",
    signal,
  });
};

export const getVisitSummaryQueryKey = () => {
  return [`/v1/visit/summary`] as const;
};

export const getVisitSummaryQueryOptions = <
  TData = Awaited<ReturnType<typeof visitSummary>>,
  TError = unknown
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof visitSummary>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getVisitSummaryQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof visitSummary>>> = ({
    signal,
  }) => visitSummary(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof visitSummary>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type VisitSummaryQueryResult = NonNullable<
  Awaited<ReturnType<typeof visitSummary>>
>;
export type VisitSummaryQueryError = unknown;

export function useVisitSummary<
  TData = Awaited<ReturnType<typeof visitSummary>>,
  TError = unknown
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof visitSummary>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof visitSummary>>,
          TError,
          Awaited<ReturnType<typeof visitSummary>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useVisitSummary<
  TData = Awaited<ReturnType<typeof visitSummary>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof visitSummary>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof visitSummary>>,
          TError,
          Awaited<ReturnType<typeof visitSummary>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useVisitSummary<
  TData = Awaited<ReturnType<typeof visitSummary>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof visitSummary>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 접속 통계 요약
 */

export function useVisitSummary<
  TData = Awaited<ReturnType<typeof visitSummary>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof visitSummary>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getVisitSummaryQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
