/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * GraceOn Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  PointGrantRequest,
  PointLedgerSearchRequest,
  PointMemberDetailParams,
  ResultDTOPointLedgerListItem,
  ResultDTOResInfinityListPointLedgerListItem,
} from "../graceOnAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * 검색/필터/페이지네이션된 포인트 원장 목록을 반환한다.
 * @summary 포인트 원장 목록
 */
export const pointList = (
  pointLedgerSearchRequest: PointLedgerSearchRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOResInfinityListPointLedgerListItem>({
    url: `/v1/point/list`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: pointLedgerSearchRequest,
    signal,
  });
};

export const getPointListMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof pointList>>,
    TError,
    { data: PointLedgerSearchRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof pointList>>,
  TError,
  { data: PointLedgerSearchRequest },
  TContext
> => {
  const mutationKey = ["pointList"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof pointList>>,
    { data: PointLedgerSearchRequest }
  > = (props) => {
    const { data } = props ?? {};

    return pointList(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PointListMutationResult = NonNullable<
  Awaited<ReturnType<typeof pointList>>
>;
export type PointListMutationBody = PointLedgerSearchRequest;
export type PointListMutationError = unknown;

/**
 * @summary 포인트 원장 목록
 */
export const usePointList = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof pointList>>,
      TError,
      { data: PointLedgerSearchRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof pointList>>,
  TError,
  { data: PointLedgerSearchRequest },
  TContext
> => {
  const mutationOptions = getPointListMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 원장 기록과 회원 누적 포인트를 한 트랜잭션에서 동기화한다. delta 음수는 차감.
 * @summary 포인트 수동 지급/차감
 */
export const pointGrant = (
  pointGrantRequest: PointGrantRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOPointLedgerListItem>({
    url: `/v1/point/grant`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: pointGrantRequest,
    signal,
  });
};

export const getPointGrantMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof pointGrant>>,
    TError,
    { data: PointGrantRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof pointGrant>>,
  TError,
  { data: PointGrantRequest },
  TContext
> => {
  const mutationKey = ["pointGrant"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof pointGrant>>,
    { data: PointGrantRequest }
  > = (props) => {
    const { data } = props ?? {};

    return pointGrant(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PointGrantMutationResult = NonNullable<
  Awaited<ReturnType<typeof pointGrant>>
>;
export type PointGrantMutationBody = PointGrantRequest;
export type PointGrantMutationError = unknown;

/**
 * @summary 포인트 수동 지급/차감
 */
export const usePointGrant = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof pointGrant>>,
      TError,
      { data: PointGrantRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof pointGrant>>,
  TError,
  { data: PointGrantRequest },
  TContext
> => {
  const mutationOptions = getPointGrantMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 회원 상세 포인트 탭용. 해당 회원의 원장을 페이지네이션해 반환한다.
 * @summary 회원별 포인트 원장
 */
export const pointMemberDetail = (
  memberId: number,
  params?: PointMemberDetailParams,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOResInfinityListPointLedgerListItem>({
    url: `/v1/point/member/${memberId}`,
    method: "GET",
    params,
    signal,
  });
};

export const getPointMemberDetailQueryKey = (
  memberId?: number,
  params?: PointMemberDetailParams
) => {
  return [`/v1/point/member/${memberId}`, ...(params ? [params] : [])] as const;
};

export const getPointMemberDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof pointMemberDetail>>,
  TError = unknown
>(
  memberId: number,
  params?: PointMemberDetailParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof pointMemberDetail>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getPointMemberDetailQueryKey(memberId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof pointMemberDetail>>
  > = ({ signal }) => pointMemberDetail(memberId, params, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!memberId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof pointMemberDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PointMemberDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof pointMemberDetail>>
>;
export type PointMemberDetailQueryError = unknown;

export function usePointMemberDetail<
  TData = Awaited<ReturnType<typeof pointMemberDetail>>,
  TError = unknown
>(
  memberId: number,
  params: undefined | PointMemberDetailParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof pointMemberDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof pointMemberDetail>>,
          TError,
          Awaited<ReturnType<typeof pointMemberDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePointMemberDetail<
  TData = Awaited<ReturnType<typeof pointMemberDetail>>,
  TError = unknown
>(
  memberId: number,
  params?: PointMemberDetailParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof pointMemberDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof pointMemberDetail>>,
          TError,
          Awaited<ReturnType<typeof pointMemberDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePointMemberDetail<
  TData = Awaited<ReturnType<typeof pointMemberDetail>>,
  TError = unknown
>(
  memberId: number,
  params?: PointMemberDetailParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof pointMemberDetail>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 회원별 포인트 원장
 */

export function usePointMemberDetail<
  TData = Awaited<ReturnType<typeof pointMemberDetail>>,
  TError = unknown
>(
  memberId: number,
  params?: PointMemberDetailParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof pointMemberDetail>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPointMemberDetailQueryOptions(
    memberId,
    params,
    options
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
