/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * GraceOn Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  PlaylistSaveRequest,
  ResultDTOListPlaylistDto,
  ResultDTOPlaylistDetail,
  ResultDTOVoid,
} from "../graceOnAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * 수록 트랙 포함.
 * @summary 플레이리스트 상세
 */
export const playlistDetail = (id: number, signal?: AbortSignal) => {
  return customInstance<ResultDTOPlaylistDetail>({
    url: `/v1/playlist/${id}`,
    method: "GET",
    signal,
  });
};

export const getPlaylistDetailQueryKey = (id?: number) => {
  return [`/v1/playlist/${id}`] as const;
};

export const getPlaylistDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof playlistDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof playlistDetail>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPlaylistDetailQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof playlistDetail>>> = ({
    signal,
  }) => playlistDetail(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof playlistDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PlaylistDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof playlistDetail>>
>;
export type PlaylistDetailQueryError = unknown;

export function usePlaylistDetail<
  TData = Awaited<ReturnType<typeof playlistDetail>>,
  TError = unknown
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof playlistDetail>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof playlistDetail>>,
          TError,
          Awaited<ReturnType<typeof playlistDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePlaylistDetail<
  TData = Awaited<ReturnType<typeof playlistDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof playlistDetail>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof playlistDetail>>,
          TError,
          Awaited<ReturnType<typeof playlistDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePlaylistDetail<
  TData = Awaited<ReturnType<typeof playlistDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof playlistDetail>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 플레이리스트 상세
 */

export function usePlaylistDetail<
  TData = Awaited<ReturnType<typeof playlistDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof playlistDetail>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPlaylistDetailQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 트랙 목록은 전체 교체(순서=목록 순서).
 * @summary 플레이리스트 수정
 */
export const playlistUpdate = (
  id: number,
  playlistSaveRequest: PlaylistSaveRequest
) => {
  return customInstance<ResultDTOPlaylistDetail>({
    url: `/v1/playlist/${id}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: playlistSaveRequest,
  });
};

export const getPlaylistUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof playlistUpdate>>,
    TError,
    { id: number; data: PlaylistSaveRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof playlistUpdate>>,
  TError,
  { id: number; data: PlaylistSaveRequest },
  TContext
> => {
  const mutationKey = ["playlistUpdate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof playlistUpdate>>,
    { id: number; data: PlaylistSaveRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return playlistUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PlaylistUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof playlistUpdate>>
>;
export type PlaylistUpdateMutationBody = PlaylistSaveRequest;
export type PlaylistUpdateMutationError = unknown;

/**
 * @summary 플레이리스트 수정
 */
export const usePlaylistUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof playlistUpdate>>,
      TError,
      { id: number; data: PlaylistSaveRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof playlistUpdate>>,
  TError,
  { id: number; data: PlaylistSaveRequest },
  TContext
> => {
  const mutationOptions = getPlaylistUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 플레이리스트 삭제
 */
export const playlistDelete = (id: number) => {
  return customInstance<ResultDTOVoid>({
    url: `/v1/playlist/${id}`,
    method: "DELETE",
  });
};

export const getPlaylistDeleteMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof playlistDelete>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof playlistDelete>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["playlistDelete"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof playlistDelete>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return playlistDelete(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type PlaylistDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof playlistDelete>>
>;

export type PlaylistDeleteMutationError = unknown;

/**
 * @summary 플레이리스트 삭제
 */
export const usePlaylistDelete = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof playlistDelete>>,
      TError,
      { id: number },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof playlistDelete>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getPlaylistDeleteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 플레이리스트 목록
 */
export const playlistList = (signal?: AbortSignal) => {
  return customInstance<ResultDTOListPlaylistDto>({
    url: `/v1/playlist`,
    method: "GET",
    signal,
  });
};

export const getPlaylistListQueryKey = () => {
  return [`/v1/playlist`] as const;
};

export const getPlaylistListQueryOptions = <
  TData = Awaited<ReturnType<typeof playlistList>>,
  TError = unknown
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof playlistList>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPlaylistListQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof playlistList>>> = ({
    signal,
  }) => playlistList(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof playlistList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PlaylistListQueryResult = NonNullable<
  Awaited<ReturnType<typeof playlistList>>
>;
export type PlaylistListQueryError = unknown;

export function usePlaylistList<
  TData = Awaited<ReturnType<typeof playlistList>>,
  TError = unknown
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof playlistList>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof playlistList>>,
          TError,
          Awaited<ReturnType<typeof playlistList>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePlaylistList<
  TData = Awaited<ReturnType<typeof playlistList>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof playlistList>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof playlistList>>,
          TError,
          Awaited<ReturnType<typeof playlistList>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePlaylistList<
  TData = Awaited<ReturnType<typeof playlistList>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof playlistList>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 플레이리스트 목록
 */

export function usePlaylistList<
  TData = Awaited<ReturnType<typeof playlistList>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof playlistList>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPlaylistListQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 플레이리스트 생성
 */
export const playlistCreate = (
  playlistSaveRequest: PlaylistSaveRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOPlaylistDetail>({
    url: `/v1/playlist`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: playlistSaveRequest,
    signal,
  });
};

export const getPlaylistCreateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof playlistCreate>>,
    TError,
    { data: PlaylistSaveRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof playlistCreate>>,
  TError,
  { data: PlaylistSaveRequest },
  TContext
> => {
  const mutationKey = ["playlistCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof playlistCreate>>,
    { data: PlaylistSaveRequest }
  > = (props) => {
    const { data } = props ?? {};

    return playlistCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PlaylistCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof playlistCreate>>
>;
export type PlaylistCreateMutationBody = PlaylistSaveRequest;
export type PlaylistCreateMutationError = unknown;

/**
 * @summary 플레이리스트 생성
 */
export const usePlaylistCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof playlistCreate>>,
      TError,
      { data: PlaylistSaveRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof playlistCreate>>,
  TError,
  { data: PlaylistSaveRequest },
  TContext
> => {
  const mutationOptions = getPlaylistCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
