/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * GraceOn Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type {
  BillingCalendarRequest,
  DonationSearchRequest,
  OnceDonationRequest,
  ResultDTODonationListItem,
  ResultDTOInteger,
  ResultDTOListBillingCalendarItem,
  ResultDTOResInfinityListDonationListItem,
} from "../graceOnAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * 데모용 — 도래한 구독을 즉시 청구하고 처리 건수를 반환한다(SYSTEM 전용).
 * @summary 정기청구 수동 실행
 */
export const donationRunBilling = (signal?: AbortSignal) => {
  return customInstance<ResultDTOInteger>({
    url: `/v1/donation/run-billing`,
    method: "POST",
    signal,
  });
};

export const getDonationRunBillingMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof donationRunBilling>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof donationRunBilling>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["donationRunBilling"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof donationRunBilling>>,
    void
  > = () => {
    return donationRunBilling();
  };

  return { mutationFn, ...mutationOptions };
};

export type DonationRunBillingMutationResult = NonNullable<
  Awaited<ReturnType<typeof donationRunBilling>>
>;

export type DonationRunBillingMutationError = unknown;

/**
 * @summary 정기청구 수동 실행
 */
export const useDonationRunBilling = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof donationRunBilling>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof donationRunBilling>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getDonationRunBillingMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 수기 단건 후원 등록(테스트 모드).
 * @summary 단건 후원 등록
 */
export const donationOnce = (
  onceDonationRequest: OnceDonationRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTODonationListItem>({
    url: `/v1/donation/once`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: onceDonationRequest,
    signal,
  });
};

export const getDonationOnceMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof donationOnce>>,
    TError,
    { data: OnceDonationRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof donationOnce>>,
  TError,
  { data: OnceDonationRequest },
  TContext
> => {
  const mutationKey = ["donationOnce"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof donationOnce>>,
    { data: OnceDonationRequest }
  > = (props) => {
    const { data } = props ?? {};

    return donationOnce(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type DonationOnceMutationResult = NonNullable<
  Awaited<ReturnType<typeof donationOnce>>
>;
export type DonationOnceMutationBody = OnceDonationRequest;
export type DonationOnceMutationError = unknown;

/**
 * @summary 단건 후원 등록
 */
export const useDonationOnce = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof donationOnce>>,
      TError,
      { data: OnceDonationRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof donationOnce>>,
  TError,
  { data: OnceDonationRequest },
  TContext
> => {
  const mutationOptions = getDonationOnceMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 유형/상태/기간 필터 + 페이지네이션.
 * @summary 후원 내역 목록
 */
export const donationList = (
  donationSearchRequest: DonationSearchRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOResInfinityListDonationListItem>({
    url: `/v1/donation/list`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: donationSearchRequest,
    signal,
  });
};

export const getDonationListMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof donationList>>,
    TError,
    { data: DonationSearchRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof donationList>>,
  TError,
  { data: DonationSearchRequest },
  TContext
> => {
  const mutationKey = ["donationList"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof donationList>>,
    { data: DonationSearchRequest }
  > = (props) => {
    const { data } = props ?? {};

    return donationList(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type DonationListMutationResult = NonNullable<
  Awaited<ReturnType<typeof donationList>>
>;
export type DonationListMutationBody = DonationSearchRequest;
export type DonationListMutationError = unknown;

/**
 * @summary 후원 내역 목록
 */
export const useDonationList = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof donationList>>,
      TError,
      { data: DonationSearchRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof donationList>>,
  TError,
  { data: DonationSearchRequest },
  TContext
> => {
  const mutationOptions = getDonationListMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 활성 구독의 월별 청구 예정 집계(날짜별 건수·금액).
 * @summary 결제일정 캘린더
 */
export const donationCalendar = (
  billingCalendarRequest: BillingCalendarRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOListBillingCalendarItem>({
    url: `/v1/donation/calendar`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: billingCalendarRequest,
    signal,
  });
};

export const getDonationCalendarMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof donationCalendar>>,
    TError,
    { data: BillingCalendarRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof donationCalendar>>,
  TError,
  { data: BillingCalendarRequest },
  TContext
> => {
  const mutationKey = ["donationCalendar"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof donationCalendar>>,
    { data: BillingCalendarRequest }
  > = (props) => {
    const { data } = props ?? {};

    return donationCalendar(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type DonationCalendarMutationResult = NonNullable<
  Awaited<ReturnType<typeof donationCalendar>>
>;
export type DonationCalendarMutationBody = BillingCalendarRequest;
export type DonationCalendarMutationError = unknown;

/**
 * @summary 결제일정 캘린더
 */
export const useDonationCalendar = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof donationCalendar>>,
      TError,
      { data: BillingCalendarRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof donationCalendar>>,
  TError,
  { data: BillingCalendarRequest },
  TContext
> => {
  const mutationOptions = getDonationCalendarMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
