/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * GraceOn Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AlbumCreateRequest,
  AlbumSearchRequest,
  AlbumUploadBody,
  ResultDTOAlbumDetail,
  ResultDTOResInfinityListAlbumListItem,
  ResultDTOUploadResponse,
  ResultDTOVoid,
} from "../graceOnAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * 트랙리스트 포함.
 * @summary 앨범 상세
 */
export const albumDetail = (id: number, signal?: AbortSignal) => {
  return customInstance<ResultDTOAlbumDetail>({
    url: `/v1/album/${id}`,
    method: "GET",
    signal,
  });
};

export const getAlbumDetailQueryKey = (id?: number) => {
  return [`/v1/album/${id}`] as const;
};

export const getAlbumDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof albumDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof albumDetail>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAlbumDetailQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof albumDetail>>> = ({
    signal,
  }) => albumDetail(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof albumDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AlbumDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof albumDetail>>
>;
export type AlbumDetailQueryError = unknown;

export function useAlbumDetail<
  TData = Awaited<ReturnType<typeof albumDetail>>,
  TError = unknown
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof albumDetail>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof albumDetail>>,
          TError,
          Awaited<ReturnType<typeof albumDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAlbumDetail<
  TData = Awaited<ReturnType<typeof albumDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof albumDetail>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof albumDetail>>,
          TError,
          Awaited<ReturnType<typeof albumDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAlbumDetail<
  TData = Awaited<ReturnType<typeof albumDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof albumDetail>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 앨범 상세
 */

export function useAlbumDetail<
  TData = Awaited<ReturnType<typeof albumDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof albumDetail>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getAlbumDetailQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 트랙/브리지 GOODS_ITEM을 동기화한다.
 * @summary 앨범 수정
 */
export const albumUpdate = (
  id: number,
  albumCreateRequest: AlbumCreateRequest
) => {
  return customInstance<ResultDTOAlbumDetail>({
    url: `/v1/album/${id}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: albumCreateRequest,
  });
};

export const getAlbumUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof albumUpdate>>,
    TError,
    { id: number; data: AlbumCreateRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof albumUpdate>>,
  TError,
  { id: number; data: AlbumCreateRequest },
  TContext
> => {
  const mutationKey = ["albumUpdate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof albumUpdate>>,
    { id: number; data: AlbumCreateRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return albumUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AlbumUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof albumUpdate>>
>;
export type AlbumUpdateMutationBody = AlbumCreateRequest;
export type AlbumUpdateMutationError = unknown;

/**
 * @summary 앨범 수정
 */
export const useAlbumUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof albumUpdate>>,
      TError,
      { id: number; data: AlbumCreateRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof albumUpdate>>,
  TError,
  { id: number; data: AlbumCreateRequest },
  TContext
> => {
  const mutationOptions = getAlbumUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 트랙은 삭제, 브리지 GOODS_ITEM은 미판매 전환(주문이력 보호).
 * @summary 앨범 삭제
 */
export const albumDelete = (id: number) => {
  return customInstance<ResultDTOVoid>({
    url: `/v1/album/${id}`,
    method: "DELETE",
  });
};

export const getAlbumDeleteMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof albumDelete>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof albumDelete>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["albumDelete"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof albumDelete>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return albumDelete(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type AlbumDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof albumDelete>>
>;

export type AlbumDeleteMutationError = unknown;

/**
 * @summary 앨범 삭제
 */
export const useAlbumDelete = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof albumDelete>>,
      TError,
      { id: number },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof albumDelete>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getAlbumDeleteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 판매 활성 시 브리지 GOODS_ITEM을 자동 생성한다.
 * @summary 앨범 등록
 */
export const albumCreate = (
  albumCreateRequest: AlbumCreateRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOAlbumDetail>({
    url: `/v1/album`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: albumCreateRequest,
    signal,
  });
};

export const getAlbumCreateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof albumCreate>>,
    TError,
    { data: AlbumCreateRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof albumCreate>>,
  TError,
  { data: AlbumCreateRequest },
  TContext
> => {
  const mutationKey = ["albumCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof albumCreate>>,
    { data: AlbumCreateRequest }
  > = (props) => {
    const { data } = props ?? {};

    return albumCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AlbumCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof albumCreate>>
>;
export type AlbumCreateMutationBody = AlbumCreateRequest;
export type AlbumCreateMutationError = unknown;

/**
 * @summary 앨범 등록
 */
export const useAlbumCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof albumCreate>>,
      TError,
      { data: AlbumCreateRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof albumCreate>>,
  TError,
  { data: AlbumCreateRequest },
  TContext
> => {
  const mutationOptions = getAlbumCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 앨범 커버를 스토리지에 업로드하고 key/url을 반환한다.
 * @summary 커버 이미지 업로드
 */
export const albumUpload = (
  albumUploadBody: AlbumUploadBody,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOUploadResponse>({
    url: `/v1/album/upload`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: albumUploadBody,
    signal,
  });
};

export const getAlbumUploadMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof albumUpload>>,
    TError,
    { data: AlbumUploadBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof albumUpload>>,
  TError,
  { data: AlbumUploadBody },
  TContext
> => {
  const mutationKey = ["albumUpload"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof albumUpload>>,
    { data: AlbumUploadBody }
  > = (props) => {
    const { data } = props ?? {};

    return albumUpload(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AlbumUploadMutationResult = NonNullable<
  Awaited<ReturnType<typeof albumUpload>>
>;
export type AlbumUploadMutationBody = AlbumUploadBody;
export type AlbumUploadMutationError = unknown;

/**
 * @summary 커버 이미지 업로드
 */
export const useAlbumUpload = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof albumUpload>>,
      TError,
      { data: AlbumUploadBody },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof albumUpload>>,
  TError,
  { data: AlbumUploadBody },
  TContext
> => {
  const mutationOptions = getAlbumUploadMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 검색/필터/페이지네이션된 음반 목록.
 * @summary 앨범 목록
 */
export const albumList = (
  albumSearchRequest: AlbumSearchRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOResInfinityListAlbumListItem>({
    url: `/v1/album/list`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: albumSearchRequest,
    signal,
  });
};

export const getAlbumListMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof albumList>>,
    TError,
    { data: AlbumSearchRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof albumList>>,
  TError,
  { data: AlbumSearchRequest },
  TContext
> => {
  const mutationKey = ["albumList"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof albumList>>,
    { data: AlbumSearchRequest }
  > = (props) => {
    const { data } = props ?? {};

    return albumList(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AlbumListMutationResult = NonNullable<
  Awaited<ReturnType<typeof albumList>>
>;
export type AlbumListMutationBody = AlbumSearchRequest;
export type AlbumListMutationError = unknown;

/**
 * @summary 앨범 목록
 */
export const useAlbumList = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof albumList>>,
      TError,
      { data: AlbumSearchRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof albumList>>,
  TError,
  { data: AlbumSearchRequest },
  TContext
> => {
  const mutationOptions = getAlbumListMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
