/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * StreamHub Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type {
  ResultDTOResInfinityListSmsListItem,
  ResultDTOSmsListItem,
  SmsSearchRequest,
  SmsSendRequest,
} from "../streamHubAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * 관리자 직접 발송. 실제 발송되지 않으며 로그만 저장된다(테스트).
 * @summary 커스텀 문자 발송
 */
export const smsSendCreate = (
  smsSendRequest: SmsSendRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOSmsListItem>({
    url: `/v1/sms/send`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: smsSendRequest,
    signal,
  });
};

export const getSmsSendCreateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof smsSendCreate>>,
    TError,
    { data: SmsSendRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof smsSendCreate>>,
  TError,
  { data: SmsSendRequest },
  TContext
> => {
  const mutationKey = ["smsSendCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof smsSendCreate>>,
    { data: SmsSendRequest }
  > = (props) => {
    const { data } = props ?? {};

    return smsSendCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type SmsSendCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof smsSendCreate>>
>;
export type SmsSendCreateMutationBody = SmsSendRequest;
export type SmsSendCreateMutationError = unknown;

/**
 * @summary 커스텀 문자 발송
 */
export const useSmsSendCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof smsSendCreate>>,
      TError,
      { data: SmsSendRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof smsSendCreate>>,
  TError,
  { data: SmsSendRequest },
  TContext
> => {
  const mutationOptions = getSmsSendCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 검색/종류/기간 필터 + 페이지네이션된 발송 내역.
 * @summary 문자 발송 내역
 */
export const smsList = (
  smsSearchRequest: SmsSearchRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOResInfinityListSmsListItem>({
    url: `/v1/sms/list`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: smsSearchRequest,
    signal,
  });
};

export const getSmsListMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof smsList>>,
    TError,
    { data: SmsSearchRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof smsList>>,
  TError,
  { data: SmsSearchRequest },
  TContext
> => {
  const mutationKey = ["smsList"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof smsList>>,
    { data: SmsSearchRequest }
  > = (props) => {
    const { data } = props ?? {};

    return smsList(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type SmsListMutationResult = NonNullable<
  Awaited<ReturnType<typeof smsList>>
>;
export type SmsListMutationBody = SmsSearchRequest;
export type SmsListMutationError = unknown;

/**
 * @summary 문자 발송 내역
 */
export const useSmsList = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof smsList>>,
      TError,
      { data: SmsSearchRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof smsList>>,
  TError,
  { data: SmsSearchRequest },
  TContext
> => {
  const mutationOptions = getSmsListMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
