/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * StreamHub Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  NotificationSearchRequest,
  NotificationSendRequest,
  ResultDTOListNotificationLogDto,
  ResultDTONotificationLogDto,
  ResultDTONotificationSummaryDto,
  ResultDTOVoid,
} from "../streamHubAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * 알림을 발송한다(로그 기록만). 전체(BROADCAST) 또는 특정 회원(TARGETED, memberIds 필수). 회원은 /pub/v1/me/notifications 피드에서 확인.
 * @summary 알림 발송
 */
export const notificationSendCreate = (
  notificationSendRequest: NotificationSendRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTONotificationLogDto>({
    url: `/v1/notification/send`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: notificationSendRequest,
    signal,
  });
};

export const getNotificationSendCreateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof notificationSendCreate>>,
    TError,
    { data: NotificationSendRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof notificationSendCreate>>,
  TError,
  { data: NotificationSendRequest },
  TContext
> => {
  const mutationKey = ["notificationSendCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof notificationSendCreate>>,
    { data: NotificationSendRequest }
  > = (props) => {
    const { data } = props ?? {};

    return notificationSendCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type NotificationSendCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof notificationSendCreate>>
>;
export type NotificationSendCreateMutationBody = NotificationSendRequest;
export type NotificationSendCreateMutationError = unknown;

/**
 * @summary 알림 발송
 */
export const useNotificationSendCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof notificationSendCreate>>,
      TError,
      { data: NotificationSendRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof notificationSendCreate>>,
  TError,
  { data: NotificationSendRequest },
  TContext
> => {
  const mutationOptions = getNotificationSendCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 채널/상태/기간/키워드 필터 적용(최신순).
 * @summary 발송 로그 목록
 */
export const notificationList = (
  notificationSearchRequest: NotificationSearchRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOListNotificationLogDto>({
    url: `/v1/notification/list`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: notificationSearchRequest,
    signal,
  });
};

export const getNotificationListMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof notificationList>>,
    TError,
    { data: NotificationSearchRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof notificationList>>,
  TError,
  { data: NotificationSearchRequest },
  TContext
> => {
  const mutationKey = ["notificationList"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof notificationList>>,
    { data: NotificationSearchRequest }
  > = (props) => {
    const { data } = props ?? {};

    return notificationList(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type NotificationListMutationResult = NonNullable<
  Awaited<ReturnType<typeof notificationList>>
>;
export type NotificationListMutationBody = NotificationSearchRequest;
export type NotificationListMutationError = unknown;

/**
 * @summary 발송 로그 목록
 */
export const useNotificationList = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof notificationList>>,
      TError,
      { data: NotificationSearchRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof notificationList>>,
  TError,
  { data: NotificationSearchRequest },
  TContext
> => {
  const mutationOptions = getNotificationListMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 발송 로그 상세
 */
export const notificationDetail = (id: number, signal?: AbortSignal) => {
  return customInstance<ResultDTONotificationLogDto>({
    url: `/v1/notification/${id}`,
    method: "GET",
    signal,
  });
};

export const getNotificationDetailQueryKey = (id?: number) => {
  return [`/v1/notification/${id}`] as const;
};

export const getNotificationDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof notificationDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof notificationDetail>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getNotificationDetailQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof notificationDetail>>
  > = ({ signal }) => notificationDetail(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof notificationDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type NotificationDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof notificationDetail>>
>;
export type NotificationDetailQueryError = unknown;

export function useNotificationDetail<
  TData = Awaited<ReturnType<typeof notificationDetail>>,
  TError = unknown
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof notificationDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof notificationDetail>>,
          TError,
          Awaited<ReturnType<typeof notificationDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useNotificationDetail<
  TData = Awaited<ReturnType<typeof notificationDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof notificationDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof notificationDetail>>,
          TError,
          Awaited<ReturnType<typeof notificationDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useNotificationDetail<
  TData = Awaited<ReturnType<typeof notificationDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof notificationDetail>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 발송 로그 상세
 */

export function useNotificationDetail<
  TData = Awaited<ReturnType<typeof notificationDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof notificationDetail>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getNotificationDetailQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 발송 로그 삭제
 */
export const notificationDelete = (id: number) => {
  return customInstance<ResultDTOVoid>({
    url: `/v1/notification/${id}`,
    method: "DELETE",
  });
};

export const getNotificationDeleteMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof notificationDelete>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof notificationDelete>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["notificationDelete"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof notificationDelete>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return notificationDelete(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type NotificationDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof notificationDelete>>
>;

export type NotificationDeleteMutationError = unknown;

/**
 * @summary 발송 로그 삭제
 */
export const useNotificationDelete = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof notificationDelete>>,
      TError,
      { id: number },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof notificationDelete>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getNotificationDeleteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 상태별 합계와 채널별(SMS/PUSH/EMAIL) 건수.
 * @summary 발송 로그 요약
 */
export const notificationSummary = (signal?: AbortSignal) => {
  return customInstance<ResultDTONotificationSummaryDto>({
    url: `/v1/notification/summary`,
    method: "GET",
    signal,
  });
};

export const getNotificationSummaryQueryKey = () => {
  return [`/v1/notification/summary`] as const;
};

export const getNotificationSummaryQueryOptions = <
  TData = Awaited<ReturnType<typeof notificationSummary>>,
  TError = unknown
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof notificationSummary>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getNotificationSummaryQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof notificationSummary>>
  > = ({ signal }) => notificationSummary(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof notificationSummary>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type NotificationSummaryQueryResult = NonNullable<
  Awaited<ReturnType<typeof notificationSummary>>
>;
export type NotificationSummaryQueryError = unknown;

export function useNotificationSummary<
  TData = Awaited<ReturnType<typeof notificationSummary>>,
  TError = unknown
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof notificationSummary>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof notificationSummary>>,
          TError,
          Awaited<ReturnType<typeof notificationSummary>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useNotificationSummary<
  TData = Awaited<ReturnType<typeof notificationSummary>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof notificationSummary>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof notificationSummary>>,
          TError,
          Awaited<ReturnType<typeof notificationSummary>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useNotificationSummary<
  TData = Awaited<ReturnType<typeof notificationSummary>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof notificationSummary>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 발송 로그 요약
 */

export function useNotificationSummary<
  TData = Awaited<ReturnType<typeof notificationSummary>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof notificationSummary>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getNotificationSummaryQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
