/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * GraceOn Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AnnouncementDto,
  AnnouncementSearchRequest,
  AnnouncementSortRequest,
  ResultDTOAnnouncementDto,
  ResultDTOListAnnouncementDto,
  ResultDTOVoid,
} from "../graceOnAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * @summary 안내창 상세
 */
export const announcementDetail = (id: number, signal?: AbortSignal) => {
  return customInstance<ResultDTOAnnouncementDto>({
    url: `/v1/announcement/${id}`,
    method: "GET",
    signal,
  });
};

export const getAnnouncementDetailQueryKey = (id?: number) => {
  return [`/v1/announcement/${id}`] as const;
};

export const getAnnouncementDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof announcementDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof announcementDetail>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAnnouncementDetailQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof announcementDetail>>
  > = ({ signal }) => announcementDetail(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof announcementDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AnnouncementDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof announcementDetail>>
>;
export type AnnouncementDetailQueryError = unknown;

export function useAnnouncementDetail<
  TData = Awaited<ReturnType<typeof announcementDetail>>,
  TError = unknown
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof announcementDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof announcementDetail>>,
          TError,
          Awaited<ReturnType<typeof announcementDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAnnouncementDetail<
  TData = Awaited<ReturnType<typeof announcementDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof announcementDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof announcementDetail>>,
          TError,
          Awaited<ReturnType<typeof announcementDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAnnouncementDetail<
  TData = Awaited<ReturnType<typeof announcementDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof announcementDetail>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 안내창 상세
 */

export function useAnnouncementDetail<
  TData = Awaited<ReturnType<typeof announcementDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof announcementDetail>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getAnnouncementDetailQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 안내창 수정
 */
export const announcementUpdate = (
  id: number,
  announcementDto: AnnouncementDto
) => {
  return customInstance<ResultDTOAnnouncementDto>({
    url: `/v1/announcement/${id}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: announcementDto,
  });
};

export const getAnnouncementUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof announcementUpdate>>,
    TError,
    { id: number; data: AnnouncementDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof announcementUpdate>>,
  TError,
  { id: number; data: AnnouncementDto },
  TContext
> => {
  const mutationKey = ["announcementUpdate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof announcementUpdate>>,
    { id: number; data: AnnouncementDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return announcementUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AnnouncementUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof announcementUpdate>>
>;
export type AnnouncementUpdateMutationBody = AnnouncementDto;
export type AnnouncementUpdateMutationError = unknown;

/**
 * @summary 안내창 수정
 */
export const useAnnouncementUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof announcementUpdate>>,
      TError,
      { id: number; data: AnnouncementDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof announcementUpdate>>,
  TError,
  { id: number; data: AnnouncementDto },
  TContext
> => {
  const mutationOptions = getAnnouncementUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 안내창 삭제
 */
export const announcementDelete = (id: number) => {
  return customInstance<ResultDTOVoid>({
    url: `/v1/announcement/${id}`,
    method: "DELETE",
  });
};

export const getAnnouncementDeleteMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof announcementDelete>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof announcementDelete>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["announcementDelete"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof announcementDelete>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return announcementDelete(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type AnnouncementDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof announcementDelete>>
>;

export type AnnouncementDeleteMutationError = unknown;

/**
 * @summary 안내창 삭제
 */
export const useAnnouncementDelete = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof announcementDelete>>,
      TError,
      { id: number },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof announcementDelete>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getAnnouncementDeleteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 정렬순서 단건 변경.
 * @summary 안내창 정렬순서 변경
 */
export const announcementSortUpdate = (
  id: number,
  announcementSortRequest: AnnouncementSortRequest
) => {
  return customInstance<ResultDTOAnnouncementDto>({
    url: `/v1/announcement/${id}/sort`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: announcementSortRequest,
  });
};

export const getAnnouncementSortUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof announcementSortUpdate>>,
    TError,
    { id: number; data: AnnouncementSortRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof announcementSortUpdate>>,
  TError,
  { id: number; data: AnnouncementSortRequest },
  TContext
> => {
  const mutationKey = ["announcementSortUpdate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof announcementSortUpdate>>,
    { id: number; data: AnnouncementSortRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return announcementSortUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AnnouncementSortUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof announcementSortUpdate>>
>;
export type AnnouncementSortUpdateMutationBody = AnnouncementSortRequest;
export type AnnouncementSortUpdateMutationError = unknown;

/**
 * @summary 안내창 정렬순서 변경
 */
export const useAnnouncementSortUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof announcementSortUpdate>>,
      TError,
      { id: number; data: AnnouncementSortRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof announcementSortUpdate>>,
  TError,
  { id: number; data: AnnouncementSortRequest },
  TContext
> => {
  const mutationOptions = getAnnouncementSortUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 안내창 등록
 */
export const announcementCreate = (
  announcementDto: AnnouncementDto,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOAnnouncementDto>({
    url: `/v1/announcement`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: announcementDto,
    signal,
  });
};

export const getAnnouncementCreateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof announcementCreate>>,
    TError,
    { data: AnnouncementDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof announcementCreate>>,
  TError,
  { data: AnnouncementDto },
  TContext
> => {
  const mutationKey = ["announcementCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof announcementCreate>>,
    { data: AnnouncementDto }
  > = (props) => {
    const { data } = props ?? {};

    return announcementCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AnnouncementCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof announcementCreate>>
>;
export type AnnouncementCreateMutationBody = AnnouncementDto;
export type AnnouncementCreateMutationError = unknown;

/**
 * @summary 안내창 등록
 */
export const useAnnouncementCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof announcementCreate>>,
      TError,
      { data: AnnouncementDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof announcementCreate>>,
  TError,
  { data: AnnouncementDto },
  TContext
> => {
  const mutationOptions = getAnnouncementCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 노출여부 필터, 정렬순서 오름차순 목록.
 * @summary 안내창 목록
 */
export const announcementList = (
  announcementSearchRequest: AnnouncementSearchRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOListAnnouncementDto>({
    url: `/v1/announcement/list`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: announcementSearchRequest,
    signal,
  });
};

export const getAnnouncementListMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof announcementList>>,
    TError,
    { data: AnnouncementSearchRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof announcementList>>,
  TError,
  { data: AnnouncementSearchRequest },
  TContext
> => {
  const mutationKey = ["announcementList"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof announcementList>>,
    { data: AnnouncementSearchRequest }
  > = (props) => {
    const { data } = props ?? {};

    return announcementList(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AnnouncementListMutationResult = NonNullable<
  Awaited<ReturnType<typeof announcementList>>
>;
export type AnnouncementListMutationBody = AnnouncementSearchRequest;
export type AnnouncementListMutationError = unknown;

/**
 * @summary 안내창 목록
 */
export const useAnnouncementList = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof announcementList>>,
      TError,
      { data: AnnouncementSearchRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof announcementList>>,
  TError,
  { data: AnnouncementSearchRequest },
  TContext
> => {
  const mutationOptions = getAnnouncementListMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
