/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * GraceOn Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { ResultDTOListMyCouponItem } from "../graceOnAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * 현재 사용 가능한(활성·기간 내) 쿠폰 목록을 회원의 사용 여부와 함께 반환한다.
 * @summary 쿠폰함
 */
export const memberCouponsMeCoupons = (signal?: AbortSignal) => {
  return customInstance<ResultDTOListMyCouponItem>({
    url: `/pub/v1/me/coupons`,
    method: "GET",
    signal,
  });
};

export const getMemberCouponsMeCouponsQueryKey = () => {
  return [`/pub/v1/me/coupons`] as const;
};

export const getMemberCouponsMeCouponsQueryOptions = <
  TData = Awaited<ReturnType<typeof memberCouponsMeCoupons>>,
  TError = unknown
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof memberCouponsMeCoupons>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getMemberCouponsMeCouponsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof memberCouponsMeCoupons>>
  > = ({ signal }) => memberCouponsMeCoupons(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof memberCouponsMeCoupons>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type MemberCouponsMeCouponsQueryResult = NonNullable<
  Awaited<ReturnType<typeof memberCouponsMeCoupons>>
>;
export type MemberCouponsMeCouponsQueryError = unknown;

export function useMemberCouponsMeCoupons<
  TData = Awaited<ReturnType<typeof memberCouponsMeCoupons>>,
  TError = unknown
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof memberCouponsMeCoupons>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof memberCouponsMeCoupons>>,
          TError,
          Awaited<ReturnType<typeof memberCouponsMeCoupons>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMemberCouponsMeCoupons<
  TData = Awaited<ReturnType<typeof memberCouponsMeCoupons>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof memberCouponsMeCoupons>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof memberCouponsMeCoupons>>,
          TError,
          Awaited<ReturnType<typeof memberCouponsMeCoupons>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMemberCouponsMeCoupons<
  TData = Awaited<ReturnType<typeof memberCouponsMeCoupons>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof memberCouponsMeCoupons>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 쿠폰함
 */

export function useMemberCouponsMeCoupons<
  TData = Awaited<ReturnType<typeof memberCouponsMeCoupons>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof memberCouponsMeCoupons>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getMemberCouponsMeCouponsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
