/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * StreamHub Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ResultDTOSiteConfigData,
  SiteConfigData,
} from "../streamHubAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * 현재 운영 UI 설정을 반환한다(미설정 시 기본값).
 * @summary 사이트 설정 조회
 */
export const siteConfigDetail = (signal?: AbortSignal) => {
  return customInstance<ResultDTOSiteConfigData>({
    url: `/v1/site-config`,
    method: "GET",
    signal,
  });
};

export const getSiteConfigDetailQueryKey = () => {
  return [`/v1/site-config`] as const;
};

export const getSiteConfigDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof siteConfigDetail>>,
  TError = unknown
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof siteConfigDetail>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSiteConfigDetailQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof siteConfigDetail>>
  > = ({ signal }) => siteConfigDetail(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof siteConfigDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SiteConfigDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof siteConfigDetail>>
>;
export type SiteConfigDetailQueryError = unknown;

export function useSiteConfigDetail<
  TData = Awaited<ReturnType<typeof siteConfigDetail>>,
  TError = unknown
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof siteConfigDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof siteConfigDetail>>,
          TError,
          Awaited<ReturnType<typeof siteConfigDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSiteConfigDetail<
  TData = Awaited<ReturnType<typeof siteConfigDetail>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof siteConfigDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof siteConfigDetail>>,
          TError,
          Awaited<ReturnType<typeof siteConfigDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSiteConfigDetail<
  TData = Awaited<ReturnType<typeof siteConfigDetail>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof siteConfigDetail>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 사이트 설정 조회
 */

export function useSiteConfigDetail<
  TData = Awaited<ReturnType<typeof siteConfigDetail>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof siteConfigDetail>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSiteConfigDetailQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 운영 UI 설정을 저장한다(단일 레코드 upsert).
 * @summary 사이트 설정 저장
 */
export const siteConfigUpdate = (siteConfigData: SiteConfigData) => {
  return customInstance<ResultDTOSiteConfigData>({
    url: `/v1/site-config`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: siteConfigData,
  });
};

export const getSiteConfigUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof siteConfigUpdate>>,
    TError,
    { data: SiteConfigData },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof siteConfigUpdate>>,
  TError,
  { data: SiteConfigData },
  TContext
> => {
  const mutationKey = ["siteConfigUpdate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof siteConfigUpdate>>,
    { data: SiteConfigData }
  > = (props) => {
    const { data } = props ?? {};

    return siteConfigUpdate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type SiteConfigUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof siteConfigUpdate>>
>;
export type SiteConfigUpdateMutationBody = SiteConfigData;
export type SiteConfigUpdateMutationError = unknown;

/**
 * @summary 사이트 설정 저장
 */
export const useSiteConfigUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof siteConfigUpdate>>,
      TError,
      { data: SiteConfigData },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof siteConfigUpdate>>,
  TError,
  { data: SiteConfigData },
  TContext
> => {
  const mutationOptions = getSiteConfigUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
