/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * GraceOn Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ChatKnowledgeDto,
  ChatReplyRequest,
  ResultDTOChatKnowledgeDto,
  ResultDTOChatMessageRow,
  ResultDTOChatStatsDto,
  ResultDTOListChatKnowledgeDto,
  ResultDTOListChatMessageRow,
  ResultDTOListChatSessionRow,
  ResultDTOListChatUnansweredDto,
  ResultDTOVoid,
} from "../graceOnAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * 지식 등록/무시 후 학습 큐에서 제거(처리완료 표시).
 * @summary 미답변 처리완료
 */
export const chatAdminUnansweredResolveUpdate = (id: number) => {
  return customInstance<ResultDTOVoid>({
    url: `/v1/chat-admin/unanswered/${id}/resolve`,
    method: "PUT",
  });
};

export const getChatAdminUnansweredResolveUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof chatAdminUnansweredResolveUpdate>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof chatAdminUnansweredResolveUpdate>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["chatAdminUnansweredResolveUpdate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof chatAdminUnansweredResolveUpdate>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return chatAdminUnansweredResolveUpdate(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type ChatAdminUnansweredResolveUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof chatAdminUnansweredResolveUpdate>>
>;

export type ChatAdminUnansweredResolveUpdateMutationError = unknown;

/**
 * @summary 미답변 처리완료
 */
export const useChatAdminUnansweredResolveUpdate = <
  TError = unknown,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof chatAdminUnansweredResolveUpdate>>,
      TError,
      { id: number },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof chatAdminUnansweredResolveUpdate>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions =
    getChatAdminUnansweredResolveUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 챗봇 지식 수정
 */
export const chatAdminKnowledgeUpdate = (
  id: number,
  chatKnowledgeDto: ChatKnowledgeDto
) => {
  return customInstance<ResultDTOChatKnowledgeDto>({
    url: `/v1/chat-admin/knowledge/${id}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: chatKnowledgeDto,
  });
};

export const getChatAdminKnowledgeUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof chatAdminKnowledgeUpdate>>,
    TError,
    { id: number; data: ChatKnowledgeDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof chatAdminKnowledgeUpdate>>,
  TError,
  { id: number; data: ChatKnowledgeDto },
  TContext
> => {
  const mutationKey = ["chatAdminKnowledgeUpdate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof chatAdminKnowledgeUpdate>>,
    { id: number; data: ChatKnowledgeDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return chatAdminKnowledgeUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ChatAdminKnowledgeUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof chatAdminKnowledgeUpdate>>
>;
export type ChatAdminKnowledgeUpdateMutationBody = ChatKnowledgeDto;
export type ChatAdminKnowledgeUpdateMutationError = unknown;

/**
 * @summary 챗봇 지식 수정
 */
export const useChatAdminKnowledgeUpdate = <
  TError = unknown,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof chatAdminKnowledgeUpdate>>,
      TError,
      { id: number; data: ChatKnowledgeDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof chatAdminKnowledgeUpdate>>,
  TError,
  { id: number; data: ChatKnowledgeDto },
  TContext
> => {
  const mutationOptions = getChatAdminKnowledgeUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 챗봇 지식 삭제
 */
export const chatAdminKnowledgeDelete = (id: number) => {
  return customInstance<ResultDTOVoid>({
    url: `/v1/chat-admin/knowledge/${id}`,
    method: "DELETE",
  });
};

export const getChatAdminKnowledgeDeleteMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof chatAdminKnowledgeDelete>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof chatAdminKnowledgeDelete>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["chatAdminKnowledgeDelete"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof chatAdminKnowledgeDelete>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return chatAdminKnowledgeDelete(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type ChatAdminKnowledgeDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof chatAdminKnowledgeDelete>>
>;

export type ChatAdminKnowledgeDeleteMutationError = unknown;

/**
 * @summary 챗봇 지식 삭제
 */
export const useChatAdminKnowledgeDelete = <
  TError = unknown,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof chatAdminKnowledgeDelete>>,
      TError,
      { id: number },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof chatAdminKnowledgeDelete>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getChatAdminKnowledgeDeleteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 최근 활동순 세션 목록. 마지막 메시지/미응답 여부 포함.
 * @summary 상담 세션 목록
 */
export const chatAdminSessionsCreate = (signal?: AbortSignal) => {
  return customInstance<ResultDTOListChatSessionRow>({
    url: `/v1/chat-admin/sessions`,
    method: "POST",
    signal,
  });
};

export const getChatAdminSessionsCreateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof chatAdminSessionsCreate>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof chatAdminSessionsCreate>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["chatAdminSessionsCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof chatAdminSessionsCreate>>,
    void
  > = () => {
    return chatAdminSessionsCreate();
  };

  return { mutationFn, ...mutationOptions };
};

export type ChatAdminSessionsCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof chatAdminSessionsCreate>>
>;

export type ChatAdminSessionsCreateMutationError = unknown;

/**
 * @summary 상담 세션 목록
 */
export const useChatAdminSessionsCreate = <
  TError = unknown,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof chatAdminSessionsCreate>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof chatAdminSessionsCreate>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getChatAdminSessionsCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 해당 세션에 운영자(BOT) 답변을 추가한다.
 * @summary 상담원 수동 답변
 */
export const chatAdminSessionsReplyCreate = (
  sessionKey: string,
  chatReplyRequest: ChatReplyRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOChatMessageRow>({
    url: `/v1/chat-admin/sessions/${sessionKey}/reply`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: chatReplyRequest,
    signal,
  });
};

export const getChatAdminSessionsReplyCreateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof chatAdminSessionsReplyCreate>>,
    TError,
    { sessionKey: string; data: ChatReplyRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof chatAdminSessionsReplyCreate>>,
  TError,
  { sessionKey: string; data: ChatReplyRequest },
  TContext
> => {
  const mutationKey = ["chatAdminSessionsReplyCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof chatAdminSessionsReplyCreate>>,
    { sessionKey: string; data: ChatReplyRequest }
  > = (props) => {
    const { sessionKey, data } = props ?? {};

    return chatAdminSessionsReplyCreate(sessionKey, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ChatAdminSessionsReplyCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof chatAdminSessionsReplyCreate>>
>;
export type ChatAdminSessionsReplyCreateMutationBody = ChatReplyRequest;
export type ChatAdminSessionsReplyCreateMutationError = unknown;

/**
 * @summary 상담원 수동 답변
 */
export const useChatAdminSessionsReplyCreate = <
  TError = unknown,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof chatAdminSessionsReplyCreate>>,
      TError,
      { sessionKey: string; data: ChatReplyRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof chatAdminSessionsReplyCreate>>,
  TError,
  { sessionKey: string; data: ChatReplyRequest },
  TContext
> => {
  const mutationOptions =
    getChatAdminSessionsReplyCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 챗봇이 답변에 사용하는 지식(FAQ) 목록(정렬순).
 * @summary 챗봇 지식 목록
 */
export const chatAdminKnowledge = (signal?: AbortSignal) => {
  return customInstance<ResultDTOListChatKnowledgeDto>({
    url: `/v1/chat-admin/knowledge`,
    method: "GET",
    signal,
  });
};

export const getChatAdminKnowledgeQueryKey = () => {
  return [`/v1/chat-admin/knowledge`] as const;
};

export const getChatAdminKnowledgeQueryOptions = <
  TData = Awaited<ReturnType<typeof chatAdminKnowledge>>,
  TError = unknown
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof chatAdminKnowledge>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getChatAdminKnowledgeQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof chatAdminKnowledge>>
  > = ({ signal }) => chatAdminKnowledge(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof chatAdminKnowledge>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ChatAdminKnowledgeQueryResult = NonNullable<
  Awaited<ReturnType<typeof chatAdminKnowledge>>
>;
export type ChatAdminKnowledgeQueryError = unknown;

export function useChatAdminKnowledge<
  TData = Awaited<ReturnType<typeof chatAdminKnowledge>>,
  TError = unknown
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof chatAdminKnowledge>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof chatAdminKnowledge>>,
          TError,
          Awaited<ReturnType<typeof chatAdminKnowledge>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useChatAdminKnowledge<
  TData = Awaited<ReturnType<typeof chatAdminKnowledge>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof chatAdminKnowledge>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof chatAdminKnowledge>>,
          TError,
          Awaited<ReturnType<typeof chatAdminKnowledge>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useChatAdminKnowledge<
  TData = Awaited<ReturnType<typeof chatAdminKnowledge>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof chatAdminKnowledge>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 챗봇 지식 목록
 */

export function useChatAdminKnowledge<
  TData = Awaited<ReturnType<typeof chatAdminKnowledge>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof chatAdminKnowledge>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getChatAdminKnowledgeQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 챗봇 지식 등록
 */
export const chatAdminKnowledgeCreate = (
  chatKnowledgeDto: ChatKnowledgeDto,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOChatKnowledgeDto>({
    url: `/v1/chat-admin/knowledge`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: chatKnowledgeDto,
    signal,
  });
};

export const getChatAdminKnowledgeCreateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof chatAdminKnowledgeCreate>>,
    TError,
    { data: ChatKnowledgeDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof chatAdminKnowledgeCreate>>,
  TError,
  { data: ChatKnowledgeDto },
  TContext
> => {
  const mutationKey = ["chatAdminKnowledgeCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof chatAdminKnowledgeCreate>>,
    { data: ChatKnowledgeDto }
  > = (props) => {
    const { data } = props ?? {};

    return chatAdminKnowledgeCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ChatAdminKnowledgeCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof chatAdminKnowledgeCreate>>
>;
export type ChatAdminKnowledgeCreateMutationBody = ChatKnowledgeDto;
export type ChatAdminKnowledgeCreateMutationError = unknown;

/**
 * @summary 챗봇 지식 등록
 */
export const useChatAdminKnowledgeCreate = <
  TError = unknown,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof chatAdminKnowledgeCreate>>,
      TError,
      { data: ChatKnowledgeDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof chatAdminKnowledgeCreate>>,
  TError,
  { data: ChatKnowledgeDto },
  TContext
> => {
  const mutationOptions = getChatAdminKnowledgeCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 봇이 답하지 못한(FALLBACK) 질문 큐(미처리, 최신순).
 * @summary 미답변 질문 목록
 */
export const chatAdminUnanswered = (signal?: AbortSignal) => {
  return customInstance<ResultDTOListChatUnansweredDto>({
    url: `/v1/chat-admin/unanswered`,
    method: "GET",
    signal,
  });
};

export const getChatAdminUnansweredQueryKey = () => {
  return [`/v1/chat-admin/unanswered`] as const;
};

export const getChatAdminUnansweredQueryOptions = <
  TData = Awaited<ReturnType<typeof chatAdminUnanswered>>,
  TError = unknown
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof chatAdminUnanswered>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getChatAdminUnansweredQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof chatAdminUnanswered>>
  > = ({ signal }) => chatAdminUnanswered(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof chatAdminUnanswered>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ChatAdminUnansweredQueryResult = NonNullable<
  Awaited<ReturnType<typeof chatAdminUnanswered>>
>;
export type ChatAdminUnansweredQueryError = unknown;

export function useChatAdminUnanswered<
  TData = Awaited<ReturnType<typeof chatAdminUnanswered>>,
  TError = unknown
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof chatAdminUnanswered>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof chatAdminUnanswered>>,
          TError,
          Awaited<ReturnType<typeof chatAdminUnanswered>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useChatAdminUnanswered<
  TData = Awaited<ReturnType<typeof chatAdminUnanswered>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof chatAdminUnanswered>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof chatAdminUnanswered>>,
          TError,
          Awaited<ReturnType<typeof chatAdminUnanswered>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useChatAdminUnanswered<
  TData = Awaited<ReturnType<typeof chatAdminUnanswered>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof chatAdminUnanswered>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 미답변 질문 목록
 */

export function useChatAdminUnanswered<
  TData = Awaited<ReturnType<typeof chatAdminUnanswered>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof chatAdminUnanswered>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getChatAdminUnansweredQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 세션·인텐트 분포·폴백률·일별 추이.
 * @summary 챗봇 분석 통계
 */
export const chatAdminStats = (signal?: AbortSignal) => {
  return customInstance<ResultDTOChatStatsDto>({
    url: `/v1/chat-admin/stats`,
    method: "GET",
    signal,
  });
};

export const getChatAdminStatsQueryKey = () => {
  return [`/v1/chat-admin/stats`] as const;
};

export const getChatAdminStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof chatAdminStats>>,
  TError = unknown
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof chatAdminStats>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getChatAdminStatsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof chatAdminStats>>> = ({
    signal,
  }) => chatAdminStats(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof chatAdminStats>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ChatAdminStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof chatAdminStats>>
>;
export type ChatAdminStatsQueryError = unknown;

export function useChatAdminStats<
  TData = Awaited<ReturnType<typeof chatAdminStats>>,
  TError = unknown
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof chatAdminStats>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof chatAdminStats>>,
          TError,
          Awaited<ReturnType<typeof chatAdminStats>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useChatAdminStats<
  TData = Awaited<ReturnType<typeof chatAdminStats>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof chatAdminStats>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof chatAdminStats>>,
          TError,
          Awaited<ReturnType<typeof chatAdminStats>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useChatAdminStats<
  TData = Awaited<ReturnType<typeof chatAdminStats>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof chatAdminStats>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 챗봇 분석 통계
 */

export function useChatAdminStats<
  TData = Awaited<ReturnType<typeof chatAdminStats>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof chatAdminStats>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getChatAdminStatsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 세션키 기준 전체 대화 스레드(오래된 순).
 * @summary 세션 대화 이력
 */
export const chatAdminSessionsMessages = (
  sessionKey: string,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOListChatMessageRow>({
    url: `/v1/chat-admin/sessions/${sessionKey}/messages`,
    method: "GET",
    signal,
  });
};

export const getChatAdminSessionsMessagesQueryKey = (sessionKey?: string) => {
  return [`/v1/chat-admin/sessions/${sessionKey}/messages`] as const;
};

export const getChatAdminSessionsMessagesQueryOptions = <
  TData = Awaited<ReturnType<typeof chatAdminSessionsMessages>>,
  TError = unknown
>(
  sessionKey: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof chatAdminSessionsMessages>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getChatAdminSessionsMessagesQueryKey(sessionKey);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof chatAdminSessionsMessages>>
  > = ({ signal }) => chatAdminSessionsMessages(sessionKey, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!sessionKey,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof chatAdminSessionsMessages>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ChatAdminSessionsMessagesQueryResult = NonNullable<
  Awaited<ReturnType<typeof chatAdminSessionsMessages>>
>;
export type ChatAdminSessionsMessagesQueryError = unknown;

export function useChatAdminSessionsMessages<
  TData = Awaited<ReturnType<typeof chatAdminSessionsMessages>>,
  TError = unknown
>(
  sessionKey: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof chatAdminSessionsMessages>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof chatAdminSessionsMessages>>,
          TError,
          Awaited<ReturnType<typeof chatAdminSessionsMessages>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useChatAdminSessionsMessages<
  TData = Awaited<ReturnType<typeof chatAdminSessionsMessages>>,
  TError = unknown
>(
  sessionKey: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof chatAdminSessionsMessages>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof chatAdminSessionsMessages>>,
          TError,
          Awaited<ReturnType<typeof chatAdminSessionsMessages>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useChatAdminSessionsMessages<
  TData = Awaited<ReturnType<typeof chatAdminSessionsMessages>>,
  TError = unknown
>(
  sessionKey: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof chatAdminSessionsMessages>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 세션 대화 이력
 */

export function useChatAdminSessionsMessages<
  TData = Awaited<ReturnType<typeof chatAdminSessionsMessages>>,
  TError = unknown
>(
  sessionKey: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof chatAdminSessionsMessages>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getChatAdminSessionsMessagesQueryOptions(
    sessionKey,
    options
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
