/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * StreamHub Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ChatReplyRequest,
  ResultDTOChatMessageRow,
  ResultDTOListChatMessageRow,
  ResultDTOListChatSessionRow,
} from "../streamHubAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * 최근 활동순 세션 목록. 마지막 메시지/미응답 여부 포함.
 * @summary 상담 세션 목록
 */
export const chatAdminSessionsCreate = (signal?: AbortSignal) => {
  return customInstance<ResultDTOListChatSessionRow>({
    url: `/v1/chat-admin/sessions`,
    method: "POST",
    signal,
  });
};

export const getChatAdminSessionsCreateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof chatAdminSessionsCreate>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof chatAdminSessionsCreate>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["chatAdminSessionsCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof chatAdminSessionsCreate>>,
    void
  > = () => {
    return chatAdminSessionsCreate();
  };

  return { mutationFn, ...mutationOptions };
};

export type ChatAdminSessionsCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof chatAdminSessionsCreate>>
>;

export type ChatAdminSessionsCreateMutationError = unknown;

/**
 * @summary 상담 세션 목록
 */
export const useChatAdminSessionsCreate = <
  TError = unknown,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof chatAdminSessionsCreate>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof chatAdminSessionsCreate>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getChatAdminSessionsCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 해당 세션에 운영자(BOT) 답변을 추가한다.
 * @summary 상담원 수동 답변
 */
export const chatAdminSessionsReplyCreate = (
  sessionKey: string,
  chatReplyRequest: ChatReplyRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOChatMessageRow>({
    url: `/v1/chat-admin/sessions/${sessionKey}/reply`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: chatReplyRequest,
    signal,
  });
};

export const getChatAdminSessionsReplyCreateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof chatAdminSessionsReplyCreate>>,
    TError,
    { sessionKey: string; data: ChatReplyRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof chatAdminSessionsReplyCreate>>,
  TError,
  { sessionKey: string; data: ChatReplyRequest },
  TContext
> => {
  const mutationKey = ["chatAdminSessionsReplyCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof chatAdminSessionsReplyCreate>>,
    { sessionKey: string; data: ChatReplyRequest }
  > = (props) => {
    const { sessionKey, data } = props ?? {};

    return chatAdminSessionsReplyCreate(sessionKey, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ChatAdminSessionsReplyCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof chatAdminSessionsReplyCreate>>
>;
export type ChatAdminSessionsReplyCreateMutationBody = ChatReplyRequest;
export type ChatAdminSessionsReplyCreateMutationError = unknown;

/**
 * @summary 상담원 수동 답변
 */
export const useChatAdminSessionsReplyCreate = <
  TError = unknown,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof chatAdminSessionsReplyCreate>>,
      TError,
      { sessionKey: string; data: ChatReplyRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof chatAdminSessionsReplyCreate>>,
  TError,
  { sessionKey: string; data: ChatReplyRequest },
  TContext
> => {
  const mutationOptions =
    getChatAdminSessionsReplyCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 세션키 기준 전체 대화 스레드(오래된 순).
 * @summary 세션 대화 이력
 */
export const chatAdminSessionsMessages = (
  sessionKey: string,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOListChatMessageRow>({
    url: `/v1/chat-admin/sessions/${sessionKey}/messages`,
    method: "GET",
    signal,
  });
};

export const getChatAdminSessionsMessagesQueryKey = (sessionKey?: string) => {
  return [`/v1/chat-admin/sessions/${sessionKey}/messages`] as const;
};

export const getChatAdminSessionsMessagesQueryOptions = <
  TData = Awaited<ReturnType<typeof chatAdminSessionsMessages>>,
  TError = unknown
>(
  sessionKey: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof chatAdminSessionsMessages>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getChatAdminSessionsMessagesQueryKey(sessionKey);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof chatAdminSessionsMessages>>
  > = ({ signal }) => chatAdminSessionsMessages(sessionKey, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!sessionKey,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof chatAdminSessionsMessages>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ChatAdminSessionsMessagesQueryResult = NonNullable<
  Awaited<ReturnType<typeof chatAdminSessionsMessages>>
>;
export type ChatAdminSessionsMessagesQueryError = unknown;

export function useChatAdminSessionsMessages<
  TData = Awaited<ReturnType<typeof chatAdminSessionsMessages>>,
  TError = unknown
>(
  sessionKey: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof chatAdminSessionsMessages>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof chatAdminSessionsMessages>>,
          TError,
          Awaited<ReturnType<typeof chatAdminSessionsMessages>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useChatAdminSessionsMessages<
  TData = Awaited<ReturnType<typeof chatAdminSessionsMessages>>,
  TError = unknown
>(
  sessionKey: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof chatAdminSessionsMessages>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof chatAdminSessionsMessages>>,
          TError,
          Awaited<ReturnType<typeof chatAdminSessionsMessages>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useChatAdminSessionsMessages<
  TData = Awaited<ReturnType<typeof chatAdminSessionsMessages>>,
  TError = unknown
>(
  sessionKey: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof chatAdminSessionsMessages>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 세션 대화 이력
 */

export function useChatAdminSessionsMessages<
  TData = Awaited<ReturnType<typeof chatAdminSessionsMessages>>,
  TError = unknown
>(
  sessionKey: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof chatAdminSessionsMessages>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getChatAdminSessionsMessagesQueryOptions(
    sessionKey,
    options
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
