/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * GraceOn Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ResultDTOResInfinityListSubscriptionListItem,
  ResultDTOSubscriptionDetail,
  SubscriptionSearchRequest,
  SubscriptionStatusRequest,
} from "../graceOnAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * ACTIVE/PAUSED/CANCELED 라이프사이클 전이.
 * @summary 구독 상태 전이
 */
export const subscriptionStatus = (
  id: number,
  subscriptionStatusRequest: SubscriptionStatusRequest
) => {
  return customInstance<ResultDTOSubscriptionDetail>({
    url: `/v1/subscription/${id}/status`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: subscriptionStatusRequest,
  });
};

export const getSubscriptionStatusMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof subscriptionStatus>>,
    TError,
    { id: number; data: SubscriptionStatusRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof subscriptionStatus>>,
  TError,
  { id: number; data: SubscriptionStatusRequest },
  TContext
> => {
  const mutationKey = ["subscriptionStatus"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof subscriptionStatus>>,
    { id: number; data: SubscriptionStatusRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return subscriptionStatus(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type SubscriptionStatusMutationResult = NonNullable<
  Awaited<ReturnType<typeof subscriptionStatus>>
>;
export type SubscriptionStatusMutationBody = SubscriptionStatusRequest;
export type SubscriptionStatusMutationError = unknown;

/**
 * @summary 구독 상태 전이
 */
export const useSubscriptionStatus = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof subscriptionStatus>>,
      TError,
      { id: number; data: SubscriptionStatusRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof subscriptionStatus>>,
  TError,
  { id: number; data: SubscriptionStatusRequest },
  TContext
> => {
  const mutationOptions = getSubscriptionStatusMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 검색/필터/페이지네이션된 구독 목록.
 * @summary 구독 목록
 */
export const subscriptionList = (
  subscriptionSearchRequest: SubscriptionSearchRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOResInfinityListSubscriptionListItem>({
    url: `/v1/subscription/list`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: subscriptionSearchRequest,
    signal,
  });
};

export const getSubscriptionListMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof subscriptionList>>,
    TError,
    { data: SubscriptionSearchRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof subscriptionList>>,
  TError,
  { data: SubscriptionSearchRequest },
  TContext
> => {
  const mutationKey = ["subscriptionList"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof subscriptionList>>,
    { data: SubscriptionSearchRequest }
  > = (props) => {
    const { data } = props ?? {};

    return subscriptionList(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type SubscriptionListMutationResult = NonNullable<
  Awaited<ReturnType<typeof subscriptionList>>
>;
export type SubscriptionListMutationBody = SubscriptionSearchRequest;
export type SubscriptionListMutationError = unknown;

/**
 * @summary 구독 목록
 */
export const useSubscriptionList = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof subscriptionList>>,
      TError,
      { data: SubscriptionSearchRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof subscriptionList>>,
  TError,
  { data: SubscriptionSearchRequest },
  TContext
> => {
  const mutationOptions = getSubscriptionListMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 구독 상세
 */
export const subscriptionDetail = (id: number, signal?: AbortSignal) => {
  return customInstance<ResultDTOSubscriptionDetail>({
    url: `/v1/subscription/${id}`,
    method: "GET",
    signal,
  });
};

export const getSubscriptionDetailQueryKey = (id?: number) => {
  return [`/v1/subscription/${id}`] as const;
};

export const getSubscriptionDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof subscriptionDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof subscriptionDetail>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSubscriptionDetailQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof subscriptionDetail>>
  > = ({ signal }) => subscriptionDetail(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof subscriptionDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SubscriptionDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof subscriptionDetail>>
>;
export type SubscriptionDetailQueryError = unknown;

export function useSubscriptionDetail<
  TData = Awaited<ReturnType<typeof subscriptionDetail>>,
  TError = unknown
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof subscriptionDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof subscriptionDetail>>,
          TError,
          Awaited<ReturnType<typeof subscriptionDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSubscriptionDetail<
  TData = Awaited<ReturnType<typeof subscriptionDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof subscriptionDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof subscriptionDetail>>,
          TError,
          Awaited<ReturnType<typeof subscriptionDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSubscriptionDetail<
  TData = Awaited<ReturnType<typeof subscriptionDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof subscriptionDetail>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 구독 상세
 */

export function useSubscriptionDetail<
  TData = Awaited<ReturnType<typeof subscriptionDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof subscriptionDetail>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSubscriptionDetailQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
