/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * StreamHub Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  BannerPublicBannersParams,
  ResultDTOListBannerDto,
} from "../streamHubAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * 노출 기간 내·사용중 배너만 정렬순으로 반환. position으로 위치 필터.
 * @summary 공개 배너 목록
 */
export const bannerPublicBanners = (
  params?: BannerPublicBannersParams,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOListBannerDto>({
    url: `/pub/v1/banners`,
    method: "GET",
    params,
    signal,
  });
};

export const getBannerPublicBannersQueryKey = (
  params?: BannerPublicBannersParams
) => {
  return [`/pub/v1/banners`, ...(params ? [params] : [])] as const;
};

export const getBannerPublicBannersQueryOptions = <
  TData = Awaited<ReturnType<typeof bannerPublicBanners>>,
  TError = unknown
>(
  params?: BannerPublicBannersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof bannerPublicBanners>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getBannerPublicBannersQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof bannerPublicBanners>>
  > = ({ signal }) => bannerPublicBanners(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof bannerPublicBanners>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type BannerPublicBannersQueryResult = NonNullable<
  Awaited<ReturnType<typeof bannerPublicBanners>>
>;
export type BannerPublicBannersQueryError = unknown;

export function useBannerPublicBanners<
  TData = Awaited<ReturnType<typeof bannerPublicBanners>>,
  TError = unknown
>(
  params: undefined | BannerPublicBannersParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof bannerPublicBanners>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof bannerPublicBanners>>,
          TError,
          Awaited<ReturnType<typeof bannerPublicBanners>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBannerPublicBanners<
  TData = Awaited<ReturnType<typeof bannerPublicBanners>>,
  TError = unknown
>(
  params?: BannerPublicBannersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof bannerPublicBanners>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof bannerPublicBanners>>,
          TError,
          Awaited<ReturnType<typeof bannerPublicBanners>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBannerPublicBanners<
  TData = Awaited<ReturnType<typeof bannerPublicBanners>>,
  TError = unknown
>(
  params?: BannerPublicBannersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof bannerPublicBanners>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 공개 배너 목록
 */

export function useBannerPublicBanners<
  TData = Awaited<ReturnType<typeof bannerPublicBanners>>,
  TError = unknown
>(
  params?: BannerPublicBannersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof bannerPublicBanners>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getBannerPublicBannersQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
