/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * StreamHub Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  MemberPointsMePointsParams,
  ResultDTOMemberPointsDto,
} from "../streamHubAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * 로그인 회원의 현재 포인트 잔액과 포인트 내역(최신순 페이징)을 반환한다.
 * @summary 내 포인트
 */
export const memberPointsMePoints = (
  params?: MemberPointsMePointsParams,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOMemberPointsDto>({
    url: `/pub/v1/me/points`,
    method: "GET",
    params,
    signal,
  });
};

export const getMemberPointsMePointsQueryKey = (
  params?: MemberPointsMePointsParams
) => {
  return [`/pub/v1/me/points`, ...(params ? [params] : [])] as const;
};

export const getMemberPointsMePointsQueryOptions = <
  TData = Awaited<ReturnType<typeof memberPointsMePoints>>,
  TError = unknown
>(
  params?: MemberPointsMePointsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof memberPointsMePoints>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getMemberPointsMePointsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof memberPointsMePoints>>
  > = ({ signal }) => memberPointsMePoints(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof memberPointsMePoints>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type MemberPointsMePointsQueryResult = NonNullable<
  Awaited<ReturnType<typeof memberPointsMePoints>>
>;
export type MemberPointsMePointsQueryError = unknown;

export function useMemberPointsMePoints<
  TData = Awaited<ReturnType<typeof memberPointsMePoints>>,
  TError = unknown
>(
  params: undefined | MemberPointsMePointsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof memberPointsMePoints>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof memberPointsMePoints>>,
          TError,
          Awaited<ReturnType<typeof memberPointsMePoints>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMemberPointsMePoints<
  TData = Awaited<ReturnType<typeof memberPointsMePoints>>,
  TError = unknown
>(
  params?: MemberPointsMePointsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof memberPointsMePoints>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof memberPointsMePoints>>,
          TError,
          Awaited<ReturnType<typeof memberPointsMePoints>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMemberPointsMePoints<
  TData = Awaited<ReturnType<typeof memberPointsMePoints>>,
  TError = unknown
>(
  params?: MemberPointsMePointsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof memberPointsMePoints>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 내 포인트
 */

export function useMemberPointsMePoints<
  TData = Awaited<ReturnType<typeof memberPointsMePoints>>,
  TError = unknown
>(
  params?: MemberPointsMePointsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof memberPointsMePoints>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getMemberPointsMePointsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
