/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * StreamHub Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  GoodsBulkUpdateRequest,
  GoodsCreateRequest,
  GoodsSearchRequest,
  GoodsUploadBody,
  ResultDTOGoodsDetail,
  ResultDTOInteger,
  ResultDTOListGoodsCategoryDto,
  ResultDTOResInfinityListGoodsListItem,
  ResultDTOUploadResponse,
  ResultDTOVoid,
} from "../streamHubAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * @summary 굿즈 상세
 */
export const goodsDetail = (id: number, signal?: AbortSignal) => {
  return customInstance<ResultDTOGoodsDetail>({
    url: `/v1/goods/${id}`,
    method: "GET",
    signal,
  });
};

export const getGoodsDetailQueryKey = (id?: number) => {
  return [`/v1/goods/${id}`] as const;
};

export const getGoodsDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof goodsDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof goodsDetail>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGoodsDetailQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof goodsDetail>>> = ({
    signal,
  }) => goodsDetail(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof goodsDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GoodsDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof goodsDetail>>
>;
export type GoodsDetailQueryError = unknown;

export function useGoodsDetail<
  TData = Awaited<ReturnType<typeof goodsDetail>>,
  TError = unknown
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof goodsDetail>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof goodsDetail>>,
          TError,
          Awaited<ReturnType<typeof goodsDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGoodsDetail<
  TData = Awaited<ReturnType<typeof goodsDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof goodsDetail>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof goodsDetail>>,
          TError,
          Awaited<ReturnType<typeof goodsDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGoodsDetail<
  TData = Awaited<ReturnType<typeof goodsDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof goodsDetail>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 굿즈 상세
 */

export function useGoodsDetail<
  TData = Awaited<ReturnType<typeof goodsDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof goodsDetail>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGoodsDetailQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 굿즈 수정
 */
export const goodsUpdate = (
  id: number,
  goodsCreateRequest: GoodsCreateRequest
) => {
  return customInstance<ResultDTOGoodsDetail>({
    url: `/v1/goods/${id}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: goodsCreateRequest,
  });
};

export const getGoodsUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof goodsUpdate>>,
    TError,
    { id: number; data: GoodsCreateRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof goodsUpdate>>,
  TError,
  { id: number; data: GoodsCreateRequest },
  TContext
> => {
  const mutationKey = ["goodsUpdate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof goodsUpdate>>,
    { id: number; data: GoodsCreateRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return goodsUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type GoodsUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof goodsUpdate>>
>;
export type GoodsUpdateMutationBody = GoodsCreateRequest;
export type GoodsUpdateMutationError = unknown;

/**
 * @summary 굿즈 수정
 */
export const useGoodsUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof goodsUpdate>>,
      TError,
      { id: number; data: GoodsCreateRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof goodsUpdate>>,
  TError,
  { id: number; data: GoodsCreateRequest },
  TContext
> => {
  const mutationOptions = getGoodsUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 굿즈 삭제
 */
export const goodsDelete = (id: number) => {
  return customInstance<ResultDTOVoid>({
    url: `/v1/goods/${id}`,
    method: "DELETE",
  });
};

export const getGoodsDeleteMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof goodsDelete>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof goodsDelete>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["goodsDelete"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof goodsDelete>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return goodsDelete(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type GoodsDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof goodsDelete>>
>;

export type GoodsDeleteMutationError = unknown;

/**
 * @summary 굿즈 삭제
 */
export const useGoodsDelete = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof goodsDelete>>,
      TError,
      { id: number },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof goodsDelete>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getGoodsDeleteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * AG Grid에서 변경된 행만 반영. 반영 행수를 반환.
 * @summary 굿즈 인라인 일괄수정
 */
export const goodsBulk = (goodsBulkUpdateRequest: GoodsBulkUpdateRequest) => {
  return customInstance<ResultDTOInteger>({
    url: `/v1/goods/bulk`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: goodsBulkUpdateRequest,
  });
};

export const getGoodsBulkMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof goodsBulk>>,
    TError,
    { data: GoodsBulkUpdateRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof goodsBulk>>,
  TError,
  { data: GoodsBulkUpdateRequest },
  TContext
> => {
  const mutationKey = ["goodsBulk"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof goodsBulk>>,
    { data: GoodsBulkUpdateRequest }
  > = (props) => {
    const { data } = props ?? {};

    return goodsBulk(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type GoodsBulkMutationResult = NonNullable<
  Awaited<ReturnType<typeof goodsBulk>>
>;
export type GoodsBulkMutationBody = GoodsBulkUpdateRequest;
export type GoodsBulkMutationError = unknown;

/**
 * @summary 굿즈 인라인 일괄수정
 */
export const useGoodsBulk = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof goodsBulk>>,
      TError,
      { data: GoodsBulkUpdateRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof goodsBulk>>,
  TError,
  { data: GoodsBulkUpdateRequest },
  TContext
> => {
  const mutationOptions = getGoodsBulkMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 굿즈 등록
 */
export const goodsCreate = (
  goodsCreateRequest: GoodsCreateRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOGoodsDetail>({
    url: `/v1/goods`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: goodsCreateRequest,
    signal,
  });
};

export const getGoodsCreateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof goodsCreate>>,
    TError,
    { data: GoodsCreateRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof goodsCreate>>,
  TError,
  { data: GoodsCreateRequest },
  TContext
> => {
  const mutationKey = ["goodsCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof goodsCreate>>,
    { data: GoodsCreateRequest }
  > = (props) => {
    const { data } = props ?? {};

    return goodsCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type GoodsCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof goodsCreate>>
>;
export type GoodsCreateMutationBody = GoodsCreateRequest;
export type GoodsCreateMutationError = unknown;

/**
 * @summary 굿즈 등록
 */
export const useGoodsCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof goodsCreate>>,
      TError,
      { data: GoodsCreateRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof goodsCreate>>,
  TError,
  { data: GoodsCreateRequest },
  TContext
> => {
  const mutationOptions = getGoodsCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 썸네일/추가 이미지를 스토리지에 업로드하고 key/url을 반환한다.
 * @summary 굿즈 이미지 업로드
 */
export const goodsUpload = (
  goodsUploadBody: GoodsUploadBody,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOUploadResponse>({
    url: `/v1/goods/upload`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: goodsUploadBody,
    signal,
  });
};

export const getGoodsUploadMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof goodsUpload>>,
    TError,
    { data: GoodsUploadBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof goodsUpload>>,
  TError,
  { data: GoodsUploadBody },
  TContext
> => {
  const mutationKey = ["goodsUpload"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof goodsUpload>>,
    { data: GoodsUploadBody }
  > = (props) => {
    const { data } = props ?? {};

    return goodsUpload(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type GoodsUploadMutationResult = NonNullable<
  Awaited<ReturnType<typeof goodsUpload>>
>;
export type GoodsUploadMutationBody = GoodsUploadBody;
export type GoodsUploadMutationError = unknown;

/**
 * @summary 굿즈 이미지 업로드
 */
export const useGoodsUpload = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof goodsUpload>>,
      TError,
      { data: GoodsUploadBody },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof goodsUpload>>,
  TError,
  { data: GoodsUploadBody },
  TContext
> => {
  const mutationOptions = getGoodsUploadMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 검색/필터/페이지네이션된 굿즈 상품 목록.
 * @summary 굿즈 목록
 */
export const goodsList = (
  goodsSearchRequest: GoodsSearchRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOResInfinityListGoodsListItem>({
    url: `/v1/goods/list`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: goodsSearchRequest,
    signal,
  });
};

export const getGoodsListMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof goodsList>>,
    TError,
    { data: GoodsSearchRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof goodsList>>,
  TError,
  { data: GoodsSearchRequest },
  TContext
> => {
  const mutationKey = ["goodsList"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof goodsList>>,
    { data: GoodsSearchRequest }
  > = (props) => {
    const { data } = props ?? {};

    return goodsList(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type GoodsListMutationResult = NonNullable<
  Awaited<ReturnType<typeof goodsList>>
>;
export type GoodsListMutationBody = GoodsSearchRequest;
export type GoodsListMutationError = unknown;

/**
 * @summary 굿즈 목록
 */
export const useGoodsList = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof goodsList>>,
      TError,
      { data: GoodsSearchRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof goodsList>>,
  TError,
  { data: GoodsSearchRequest },
  TContext
> => {
  const mutationOptions = getGoodsListMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 굿즈 등록 폼의 분류 선택용 트리.
 * @summary 굿즈 카테고리 트리
 */
export const goodsCategories = (signal?: AbortSignal) => {
  return customInstance<ResultDTOListGoodsCategoryDto>({
    url: `/v1/goods/categories`,
    method: "GET",
    signal,
  });
};

export const getGoodsCategoriesQueryKey = () => {
  return [`/v1/goods/categories`] as const;
};

export const getGoodsCategoriesQueryOptions = <
  TData = Awaited<ReturnType<typeof goodsCategories>>,
  TError = unknown
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof goodsCategories>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGoodsCategoriesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof goodsCategories>>> = ({
    signal,
  }) => goodsCategories(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof goodsCategories>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GoodsCategoriesQueryResult = NonNullable<
  Awaited<ReturnType<typeof goodsCategories>>
>;
export type GoodsCategoriesQueryError = unknown;

export function useGoodsCategories<
  TData = Awaited<ReturnType<typeof goodsCategories>>,
  TError = unknown
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof goodsCategories>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof goodsCategories>>,
          TError,
          Awaited<ReturnType<typeof goodsCategories>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGoodsCategories<
  TData = Awaited<ReturnType<typeof goodsCategories>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof goodsCategories>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof goodsCategories>>,
          TError,
          Awaited<ReturnType<typeof goodsCategories>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGoodsCategories<
  TData = Awaited<ReturnType<typeof goodsCategories>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof goodsCategories>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 굿즈 카테고리 트리
 */

export function useGoodsCategories<
  TData = Awaited<ReturnType<typeof goodsCategories>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof goodsCategories>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGoodsCategoriesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
