/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * GraceOn Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type {
  ResultDTOListStoreDto,
  ResultDTOStoreDto,
  ResultDTOVoid,
  StoreDto,
} from "../graceOnAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * @summary 매장 수정
 */
export const storeUpdate = (id: number, storeDto: StoreDto) => {
  return customInstance<ResultDTOStoreDto>({
    url: `/v1/store/${id}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: storeDto,
  });
};

export const getStoreUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof storeUpdate>>,
    TError,
    { id: number; data: StoreDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof storeUpdate>>,
  TError,
  { id: number; data: StoreDto },
  TContext
> => {
  const mutationKey = ["storeUpdate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof storeUpdate>>,
    { id: number; data: StoreDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return storeUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type StoreUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof storeUpdate>>
>;
export type StoreUpdateMutationBody = StoreDto;
export type StoreUpdateMutationError = unknown;

/**
 * @summary 매장 수정
 */
export const useStoreUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof storeUpdate>>,
      TError,
      { id: number; data: StoreDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof storeUpdate>>,
  TError,
  { id: number; data: StoreDto },
  TContext
> => {
  const mutationOptions = getStoreUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 매장 삭제
 */
export const storeDelete = (id: number) => {
  return customInstance<ResultDTOVoid>({
    url: `/v1/store/${id}`,
    method: "DELETE",
  });
};

export const getStoreDeleteMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof storeDelete>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof storeDelete>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["storeDelete"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof storeDelete>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return storeDelete(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type StoreDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof storeDelete>>
>;

export type StoreDeleteMutationError = unknown;

/**
 * @summary 매장 삭제
 */
export const useStoreDelete = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof storeDelete>>,
      TError,
      { id: number },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof storeDelete>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getStoreDeleteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 매장 등록
 */
export const storeCreate = (storeDto: StoreDto, signal?: AbortSignal) => {
  return customInstance<ResultDTOStoreDto>({
    url: `/v1/store`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: storeDto,
    signal,
  });
};

export const getStoreCreateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof storeCreate>>,
    TError,
    { data: StoreDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof storeCreate>>,
  TError,
  { data: StoreDto },
  TContext
> => {
  const mutationKey = ["storeCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof storeCreate>>,
    { data: StoreDto }
  > = (props) => {
    const { data } = props ?? {};

    return storeCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type StoreCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof storeCreate>>
>;
export type StoreCreateMutationBody = StoreDto;
export type StoreCreateMutationError = unknown;

/**
 * @summary 매장 등록
 */
export const useStoreCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof storeCreate>>,
      TError,
      { data: StoreDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof storeCreate>>,
  TError,
  { data: StoreDto },
  TContext
> => {
  const mutationOptions = getStoreCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 관리자용 전체 매장 목록(최신순).
 * @summary 매장 목록
 */
export const storeList = (signal?: AbortSignal) => {
  return customInstance<ResultDTOListStoreDto>({
    url: `/v1/store/list`,
    method: "POST",
    signal,
  });
};

export const getStoreListMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof storeList>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof storeList>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["storeList"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof storeList>>,
    void
  > = () => {
    return storeList();
  };

  return { mutationFn, ...mutationOptions };
};

export type StoreListMutationResult = NonNullable<
  Awaited<ReturnType<typeof storeList>>
>;

export type StoreListMutationError = unknown;

/**
 * @summary 매장 목록
 */
export const useStoreList = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof storeList>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof storeList>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getStoreListMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
