/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * GraceOn Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  MemberNotificationsMeNotificationsParams,
  ResultDTOLong,
  ResultDTOResInfinityListNotificationItem,
  ResultDTOVoid,
} from "../graceOnAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * 알림 1건을 회원의 읽음으로 기록한다(멱등). 발송된 알림이 아니면 404.
 * @summary 알림 읽음
 */
export const memberNotificationsMeNotificationsReadCreate = (
  id: number,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOVoid>({
    url: `/pub/v1/me/notifications/${id}/read`,
    method: "POST",
    signal,
  });
};

export const getMemberNotificationsMeNotificationsReadCreateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof memberNotificationsMeNotificationsReadCreate>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof memberNotificationsMeNotificationsReadCreate>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["memberNotificationsMeNotificationsReadCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof memberNotificationsMeNotificationsReadCreate>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return memberNotificationsMeNotificationsReadCreate(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type MemberNotificationsMeNotificationsReadCreateMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof memberNotificationsMeNotificationsReadCreate>>
  >;

export type MemberNotificationsMeNotificationsReadCreateMutationError = unknown;

/**
 * @summary 알림 읽음
 */
export const useMemberNotificationsMeNotificationsReadCreate = <
  TError = unknown,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof memberNotificationsMeNotificationsReadCreate>>,
      TError,
      { id: number },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof memberNotificationsMeNotificationsReadCreate>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions =
    getMemberNotificationsMeNotificationsReadCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 회원의 모든 알림을 읽음으로 기록한다.
 * @summary 알림 모두 읽음
 */
export const memberNotificationsMeNotificationsReadAllCreate = (
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOVoid>({
    url: `/pub/v1/me/notifications/read-all`,
    method: "POST",
    signal,
  });
};

export const getMemberNotificationsMeNotificationsReadAllCreateMutationOptions =
  <TError = unknown, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<
      Awaited<
        ReturnType<typeof memberNotificationsMeNotificationsReadAllCreate>
      >,
      TError,
      void,
      TContext
    >;
  }): UseMutationOptions<
    Awaited<ReturnType<typeof memberNotificationsMeNotificationsReadAllCreate>>,
    TError,
    void,
    TContext
  > => {
    const mutationKey = ["memberNotificationsMeNotificationsReadAllCreate"];
    const { mutation: mutationOptions } = options
      ? options.mutation &&
        "mutationKey" in options.mutation &&
        options.mutation.mutationKey
        ? options
        : { ...options, mutation: { ...options.mutation, mutationKey } }
      : { mutation: { mutationKey } };

    const mutationFn: MutationFunction<
      Awaited<
        ReturnType<typeof memberNotificationsMeNotificationsReadAllCreate>
      >,
      void
    > = () => {
      return memberNotificationsMeNotificationsReadAllCreate();
    };

    return { mutationFn, ...mutationOptions };
  };

export type MemberNotificationsMeNotificationsReadAllCreateMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof memberNotificationsMeNotificationsReadAllCreate>>
  >;

export type MemberNotificationsMeNotificationsReadAllCreateMutationError =
  unknown;

/**
 * @summary 알림 모두 읽음
 */
export const useMemberNotificationsMeNotificationsReadAllCreate = <
  TError = unknown,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<
        ReturnType<typeof memberNotificationsMeNotificationsReadAllCreate>
      >,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof memberNotificationsMeNotificationsReadAllCreate>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions =
    getMemberNotificationsMeNotificationsReadAllCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 최근 발송된 알림을 최신순으로 페이징해 반환한다. 각 항목의 read는 회원별 읽음 상태다.
 * @summary 내 알림 목록
 */
export const memberNotificationsMeNotifications = (
  params?: MemberNotificationsMeNotificationsParams,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOResInfinityListNotificationItem>({
    url: `/pub/v1/me/notifications`,
    method: "GET",
    params,
    signal,
  });
};

export const getMemberNotificationsMeNotificationsQueryKey = (
  params?: MemberNotificationsMeNotificationsParams
) => {
  return [`/pub/v1/me/notifications`, ...(params ? [params] : [])] as const;
};

export const getMemberNotificationsMeNotificationsQueryOptions = <
  TData = Awaited<ReturnType<typeof memberNotificationsMeNotifications>>,
  TError = unknown
>(
  params?: MemberNotificationsMeNotificationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof memberNotificationsMeNotifications>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getMemberNotificationsMeNotificationsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof memberNotificationsMeNotifications>>
  > = ({ signal }) => memberNotificationsMeNotifications(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof memberNotificationsMeNotifications>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type MemberNotificationsMeNotificationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof memberNotificationsMeNotifications>>
>;
export type MemberNotificationsMeNotificationsQueryError = unknown;

export function useMemberNotificationsMeNotifications<
  TData = Awaited<ReturnType<typeof memberNotificationsMeNotifications>>,
  TError = unknown
>(
  params: undefined | MemberNotificationsMeNotificationsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof memberNotificationsMeNotifications>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof memberNotificationsMeNotifications>>,
          TError,
          Awaited<ReturnType<typeof memberNotificationsMeNotifications>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMemberNotificationsMeNotifications<
  TData = Awaited<ReturnType<typeof memberNotificationsMeNotifications>>,
  TError = unknown
>(
  params?: MemberNotificationsMeNotificationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof memberNotificationsMeNotifications>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof memberNotificationsMeNotifications>>,
          TError,
          Awaited<ReturnType<typeof memberNotificationsMeNotifications>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMemberNotificationsMeNotifications<
  TData = Awaited<ReturnType<typeof memberNotificationsMeNotifications>>,
  TError = unknown
>(
  params?: MemberNotificationsMeNotificationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof memberNotificationsMeNotifications>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 내 알림 목록
 */

export function useMemberNotificationsMeNotifications<
  TData = Awaited<ReturnType<typeof memberNotificationsMeNotifications>>,
  TError = unknown
>(
  params?: MemberNotificationsMeNotificationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof memberNotificationsMeNotifications>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getMemberNotificationsMeNotificationsQueryOptions(
    params,
    options
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 회원이 아직 읽지 않은 알림 개수(배지용)를 반환한다.
 * @summary 안읽은 알림 수
 */
export const memberNotificationsMeNotificationsUnreadCount = (
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOLong>({
    url: `/pub/v1/me/notifications/unread-count`,
    method: "GET",
    signal,
  });
};

export const getMemberNotificationsMeNotificationsUnreadCountQueryKey = () => {
  return [`/pub/v1/me/notifications/unread-count`] as const;
};

export const getMemberNotificationsMeNotificationsUnreadCountQueryOptions = <
  TData = Awaited<
    ReturnType<typeof memberNotificationsMeNotificationsUnreadCount>
  >,
  TError = unknown
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof memberNotificationsMeNotificationsUnreadCount>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getMemberNotificationsMeNotificationsUnreadCountQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof memberNotificationsMeNotificationsUnreadCount>>
  > = ({ signal }) => memberNotificationsMeNotificationsUnreadCount(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof memberNotificationsMeNotificationsUnreadCount>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type MemberNotificationsMeNotificationsUnreadCountQueryResult =
  NonNullable<
    Awaited<ReturnType<typeof memberNotificationsMeNotificationsUnreadCount>>
  >;
export type MemberNotificationsMeNotificationsUnreadCountQueryError = unknown;

export function useMemberNotificationsMeNotificationsUnreadCount<
  TData = Awaited<
    ReturnType<typeof memberNotificationsMeNotificationsUnreadCount>
  >,
  TError = unknown
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof memberNotificationsMeNotificationsUnreadCount>
        >,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof memberNotificationsMeNotificationsUnreadCount>
          >,
          TError,
          Awaited<
            ReturnType<typeof memberNotificationsMeNotificationsUnreadCount>
          >
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMemberNotificationsMeNotificationsUnreadCount<
  TData = Awaited<
    ReturnType<typeof memberNotificationsMeNotificationsUnreadCount>
  >,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof memberNotificationsMeNotificationsUnreadCount>
        >,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof memberNotificationsMeNotificationsUnreadCount>
          >,
          TError,
          Awaited<
            ReturnType<typeof memberNotificationsMeNotificationsUnreadCount>
          >
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMemberNotificationsMeNotificationsUnreadCount<
  TData = Awaited<
    ReturnType<typeof memberNotificationsMeNotificationsUnreadCount>
  >,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof memberNotificationsMeNotificationsUnreadCount>
        >,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 안읽은 알림 수
 */

export function useMemberNotificationsMeNotificationsUnreadCount<
  TData = Awaited<
    ReturnType<typeof memberNotificationsMeNotificationsUnreadCount>
  >,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof memberNotificationsMeNotificationsUnreadCount>
        >,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getMemberNotificationsMeNotificationsUnreadCountQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
