/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * GraceOn Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { MediaPublicMediaFileParams } from "../graceOnAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * 저장된 미디어 객체(이미지 등)를 키로 스트리밍한다.
 * @summary 미디어 파일
 */
export const mediaPublicMediaFile = (
  params: MediaPublicMediaFileParams,
  signal?: AbortSignal
) => {
  return customInstance<string>({
    url: `/pub/v1/media/file`,
    method: "GET",
    params,
    signal,
  });
};

export const getMediaPublicMediaFileQueryKey = (
  params?: MediaPublicMediaFileParams
) => {
  return [`/pub/v1/media/file`, ...(params ? [params] : [])] as const;
};

export const getMediaPublicMediaFileQueryOptions = <
  TData = Awaited<ReturnType<typeof mediaPublicMediaFile>>,
  TError = unknown
>(
  params: MediaPublicMediaFileParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof mediaPublicMediaFile>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getMediaPublicMediaFileQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof mediaPublicMediaFile>>
  > = ({ signal }) => mediaPublicMediaFile(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof mediaPublicMediaFile>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type MediaPublicMediaFileQueryResult = NonNullable<
  Awaited<ReturnType<typeof mediaPublicMediaFile>>
>;
export type MediaPublicMediaFileQueryError = unknown;

export function useMediaPublicMediaFile<
  TData = Awaited<ReturnType<typeof mediaPublicMediaFile>>,
  TError = unknown
>(
  params: MediaPublicMediaFileParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof mediaPublicMediaFile>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof mediaPublicMediaFile>>,
          TError,
          Awaited<ReturnType<typeof mediaPublicMediaFile>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMediaPublicMediaFile<
  TData = Awaited<ReturnType<typeof mediaPublicMediaFile>>,
  TError = unknown
>(
  params: MediaPublicMediaFileParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof mediaPublicMediaFile>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof mediaPublicMediaFile>>,
          TError,
          Awaited<ReturnType<typeof mediaPublicMediaFile>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMediaPublicMediaFile<
  TData = Awaited<ReturnType<typeof mediaPublicMediaFile>>,
  TError = unknown
>(
  params: MediaPublicMediaFileParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof mediaPublicMediaFile>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 미디어 파일
 */

export function useMediaPublicMediaFile<
  TData = Awaited<ReturnType<typeof mediaPublicMediaFile>>,
  TError = unknown
>(
  params: MediaPublicMediaFileParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof mediaPublicMediaFile>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getMediaPublicMediaFileQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
