/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * StreamHub Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  DashboardFeedParams,
  DashboardTimeseriesParams,
  ResultDTODashboardSummaryResponse,
  ResultDTOListFeedItem,
  ResultDTOTimeseriesResponse,
} from "../streamHubAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * 최근 N일 굿즈매출/정기후원/단건후원 스택 시계열(빈 날짜 0 채움). Redis 캐싱(60s).
 * @summary 후원·매출 추이
 */
export const dashboardTimeseries = (
  params?: DashboardTimeseriesParams,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOTimeseriesResponse>({
    url: `/v1/dashboard/timeseries`,
    method: "GET",
    params,
    signal,
  });
};

export const getDashboardTimeseriesQueryKey = (
  params?: DashboardTimeseriesParams
) => {
  return [`/v1/dashboard/timeseries`, ...(params ? [params] : [])] as const;
};

export const getDashboardTimeseriesQueryOptions = <
  TData = Awaited<ReturnType<typeof dashboardTimeseries>>,
  TError = unknown
>(
  params?: DashboardTimeseriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof dashboardTimeseries>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getDashboardTimeseriesQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof dashboardTimeseries>>
  > = ({ signal }) => dashboardTimeseries(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof dashboardTimeseries>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DashboardTimeseriesQueryResult = NonNullable<
  Awaited<ReturnType<typeof dashboardTimeseries>>
>;
export type DashboardTimeseriesQueryError = unknown;

export function useDashboardTimeseries<
  TData = Awaited<ReturnType<typeof dashboardTimeseries>>,
  TError = unknown
>(
  params: undefined | DashboardTimeseriesParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof dashboardTimeseries>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof dashboardTimeseries>>,
          TError,
          Awaited<ReturnType<typeof dashboardTimeseries>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDashboardTimeseries<
  TData = Awaited<ReturnType<typeof dashboardTimeseries>>,
  TError = unknown
>(
  params?: DashboardTimeseriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof dashboardTimeseries>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof dashboardTimeseries>>,
          TError,
          Awaited<ReturnType<typeof dashboardTimeseries>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDashboardTimeseries<
  TData = Awaited<ReturnType<typeof dashboardTimeseries>>,
  TError = unknown
>(
  params?: DashboardTimeseriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof dashboardTimeseries>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 후원·매출 추이
 */

export function useDashboardTimeseries<
  TData = Awaited<ReturnType<typeof dashboardTimeseries>>,
  TError = unknown
>(
  params?: DashboardTimeseriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof dashboardTimeseries>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getDashboardTimeseriesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 오늘 후원·매출/신규구독/진행중주문/미답변문의/재고경고/활성구독자. Redis 캐싱(60s).
 * @summary KPI 요약
 */
export const dashboardSummary = (signal?: AbortSignal) => {
  return customInstance<ResultDTODashboardSummaryResponse>({
    url: `/v1/dashboard/summary`,
    method: "GET",
    signal,
  });
};

export const getDashboardSummaryQueryKey = () => {
  return [`/v1/dashboard/summary`] as const;
};

export const getDashboardSummaryQueryOptions = <
  TData = Awaited<ReturnType<typeof dashboardSummary>>,
  TError = unknown
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof dashboardSummary>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDashboardSummaryQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof dashboardSummary>>
  > = ({ signal }) => dashboardSummary(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof dashboardSummary>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DashboardSummaryQueryResult = NonNullable<
  Awaited<ReturnType<typeof dashboardSummary>>
>;
export type DashboardSummaryQueryError = unknown;

export function useDashboardSummary<
  TData = Awaited<ReturnType<typeof dashboardSummary>>,
  TError = unknown
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof dashboardSummary>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof dashboardSummary>>,
          TError,
          Awaited<ReturnType<typeof dashboardSummary>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDashboardSummary<
  TData = Awaited<ReturnType<typeof dashboardSummary>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof dashboardSummary>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof dashboardSummary>>,
          TError,
          Awaited<ReturnType<typeof dashboardSummary>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDashboardSummary<
  TData = Awaited<ReturnType<typeof dashboardSummary>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof dashboardSummary>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary KPI 요약
 */

export function useDashboardSummary<
  TData = Awaited<ReturnType<typeof dashboardSummary>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof dashboardSummary>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getDashboardSummaryQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 최근 활동 N건(주문·구독·후원 union, 최신순). 캐시 없음.
 * @summary 실시간 활동 피드
 */
export const dashboardFeed = (
  params?: DashboardFeedParams,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOListFeedItem>({
    url: `/v1/dashboard/feed`,
    method: "GET",
    params,
    signal,
  });
};

export const getDashboardFeedQueryKey = (params?: DashboardFeedParams) => {
  return [`/v1/dashboard/feed`, ...(params ? [params] : [])] as const;
};

export const getDashboardFeedQueryOptions = <
  TData = Awaited<ReturnType<typeof dashboardFeed>>,
  TError = unknown
>(
  params?: DashboardFeedParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof dashboardFeed>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDashboardFeedQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof dashboardFeed>>> = ({
    signal,
  }) => dashboardFeed(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof dashboardFeed>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DashboardFeedQueryResult = NonNullable<
  Awaited<ReturnType<typeof dashboardFeed>>
>;
export type DashboardFeedQueryError = unknown;

export function useDashboardFeed<
  TData = Awaited<ReturnType<typeof dashboardFeed>>,
  TError = unknown
>(
  params: undefined | DashboardFeedParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof dashboardFeed>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof dashboardFeed>>,
          TError,
          Awaited<ReturnType<typeof dashboardFeed>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDashboardFeed<
  TData = Awaited<ReturnType<typeof dashboardFeed>>,
  TError = unknown
>(
  params?: DashboardFeedParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof dashboardFeed>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof dashboardFeed>>,
          TError,
          Awaited<ReturnType<typeof dashboardFeed>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDashboardFeed<
  TData = Awaited<ReturnType<typeof dashboardFeed>>,
  TError = unknown
>(
  params?: DashboardFeedParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof dashboardFeed>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 실시간 활동 피드
 */

export function useDashboardFeed<
  TData = Awaited<ReturnType<typeof dashboardFeed>>,
  TError = unknown
>(
  params?: DashboardFeedParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof dashboardFeed>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getDashboardFeedQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
