/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * GraceOn Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  PasswordChangeRequest,
  ResultDTOMeResponse,
  ResultDTOVoid,
} from "../graceOnAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * 현재 비밀번호 확인 후 변경한다. 변경 시 저장된 refresh 토큰이 폐기되어 재로그인이 필요하다. 권한 검사 없이 본인 계정만 대상이므로 VIEWER 데모 계정도 자기 비밀번호는 바꿀 수 있다.
 * @summary 비밀번호 변경
 */
export const adminMePasswordCreate = (
  passwordChangeRequest: PasswordChangeRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOVoid>({
    url: `/v1/admin/me/password`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: passwordChangeRequest,
    signal,
  });
};

export const getAdminMePasswordCreateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminMePasswordCreate>>,
    TError,
    { data: PasswordChangeRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminMePasswordCreate>>,
  TError,
  { data: PasswordChangeRequest },
  TContext
> => {
  const mutationKey = ["adminMePasswordCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminMePasswordCreate>>,
    { data: PasswordChangeRequest }
  > = (props) => {
    const { data } = props ?? {};

    return adminMePasswordCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminMePasswordCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminMePasswordCreate>>
>;
export type AdminMePasswordCreateMutationBody = PasswordChangeRequest;
export type AdminMePasswordCreateMutationError = unknown;

/**
 * @summary 비밀번호 변경
 */
export const useAdminMePasswordCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminMePasswordCreate>>,
      TError,
      { data: PasswordChangeRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof adminMePasswordCreate>>,
  TError,
  { data: PasswordChangeRequest },
  TContext
> => {
  const mutationOptions = getAdminMePasswordCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 현재 인증된 운영자 정보를 반환한다.
 * @summary 내 정보
 */
export const adminMe = (signal?: AbortSignal) => {
  return customInstance<ResultDTOMeResponse>({
    url: `/v1/admin/me`,
    method: "GET",
    signal,
  });
};

export const getAdminMeQueryKey = () => {
  return [`/v1/admin/me`] as const;
};

export const getAdminMeQueryOptions = <
  TData = Awaited<ReturnType<typeof adminMe>>,
  TError = unknown
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof adminMe>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAdminMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof adminMe>>> = ({
    signal,
  }) => adminMe(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof adminMe>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AdminMeQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminMe>>
>;
export type AdminMeQueryError = unknown;

export function useAdminMe<
  TData = Awaited<ReturnType<typeof adminMe>>,
  TError = unknown
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof adminMe>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminMe>>,
          TError,
          Awaited<ReturnType<typeof adminMe>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAdminMe<
  TData = Awaited<ReturnType<typeof adminMe>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof adminMe>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminMe>>,
          TError,
          Awaited<ReturnType<typeof adminMe>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAdminMe<
  TData = Awaited<ReturnType<typeof adminMe>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof adminMe>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 내 정보
 */

export function useAdminMe<
  TData = Awaited<ReturnType<typeof adminMe>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof adminMe>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getAdminMeQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
