/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * GraceOn Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  PublicCampaignCampaignsParams,
  ResultDTOCampaignDetail,
  ResultDTOResInfinityListCampaignListItem,
} from "../graceOnAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * 공개 노출 대상(진행중) 캠페인을 시작일 최신순으로 페이징해 반환한다.
 * @summary 공개 캠페인 목록
 */
export const publicCampaignCampaigns = (
  params?: PublicCampaignCampaignsParams,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOResInfinityListCampaignListItem>({
    url: `/pub/v1/campaigns`,
    method: "GET",
    params,
    signal,
  });
};

export const getPublicCampaignCampaignsQueryKey = (
  params?: PublicCampaignCampaignsParams
) => {
  return [`/pub/v1/campaigns`, ...(params ? [params] : [])] as const;
};

export const getPublicCampaignCampaignsQueryOptions = <
  TData = Awaited<ReturnType<typeof publicCampaignCampaigns>>,
  TError = unknown
>(
  params?: PublicCampaignCampaignsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicCampaignCampaigns>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getPublicCampaignCampaignsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof publicCampaignCampaigns>>
  > = ({ signal }) => publicCampaignCampaigns(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof publicCampaignCampaigns>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PublicCampaignCampaignsQueryResult = NonNullable<
  Awaited<ReturnType<typeof publicCampaignCampaigns>>
>;
export type PublicCampaignCampaignsQueryError = unknown;

export function usePublicCampaignCampaigns<
  TData = Awaited<ReturnType<typeof publicCampaignCampaigns>>,
  TError = unknown
>(
  params: undefined | PublicCampaignCampaignsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicCampaignCampaigns>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicCampaignCampaigns>>,
          TError,
          Awaited<ReturnType<typeof publicCampaignCampaigns>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicCampaignCampaigns<
  TData = Awaited<ReturnType<typeof publicCampaignCampaigns>>,
  TError = unknown
>(
  params?: PublicCampaignCampaignsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicCampaignCampaigns>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicCampaignCampaigns>>,
          TError,
          Awaited<ReturnType<typeof publicCampaignCampaigns>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicCampaignCampaigns<
  TData = Awaited<ReturnType<typeof publicCampaignCampaigns>>,
  TError = unknown
>(
  params?: PublicCampaignCampaignsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicCampaignCampaigns>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 공개 캠페인 목록
 */

export function usePublicCampaignCampaigns<
  TData = Awaited<ReturnType<typeof publicCampaignCampaigns>>,
  TError = unknown
>(
  params?: PublicCampaignCampaignsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicCampaignCampaigns>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPublicCampaignCampaignsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 공개 노출 대상 캠페인의 상세를 반환한다. 없거나 비공개면 NOT_FOUND.
 * @summary 공개 캠페인 상세
 */
export const publicCampaignCampaignsDetail = (
  id: number,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOCampaignDetail>({
    url: `/pub/v1/campaigns/${id}`,
    method: "GET",
    signal,
  });
};

export const getPublicCampaignCampaignsDetailQueryKey = (id?: number) => {
  return [`/pub/v1/campaigns/${id}`] as const;
};

export const getPublicCampaignCampaignsDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof publicCampaignCampaignsDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicCampaignCampaignsDetail>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getPublicCampaignCampaignsDetailQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof publicCampaignCampaignsDetail>>
  > = ({ signal }) => publicCampaignCampaignsDetail(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof publicCampaignCampaignsDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PublicCampaignCampaignsDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof publicCampaignCampaignsDetail>>
>;
export type PublicCampaignCampaignsDetailQueryError = unknown;

export function usePublicCampaignCampaignsDetail<
  TData = Awaited<ReturnType<typeof publicCampaignCampaignsDetail>>,
  TError = unknown
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicCampaignCampaignsDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicCampaignCampaignsDetail>>,
          TError,
          Awaited<ReturnType<typeof publicCampaignCampaignsDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicCampaignCampaignsDetail<
  TData = Awaited<ReturnType<typeof publicCampaignCampaignsDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicCampaignCampaignsDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicCampaignCampaignsDetail>>,
          TError,
          Awaited<ReturnType<typeof publicCampaignCampaignsDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicCampaignCampaignsDetail<
  TData = Awaited<ReturnType<typeof publicCampaignCampaignsDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicCampaignCampaignsDetail>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 공개 캠페인 상세
 */

export function usePublicCampaignCampaignsDetail<
  TData = Awaited<ReturnType<typeof publicCampaignCampaignsDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicCampaignCampaignsDetail>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPublicCampaignCampaignsDetailQueryOptions(
    id,
    options
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
