/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * StreamHub Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  PublicContentsParams,
  PublicPostsParams,
  ResultDTOContentDetail,
  ResultDTOPostDetail,
  ResultDTOPublicHomeResponse,
  ResultDTOResInfinityListContentListItem,
  ResultDTOResInfinityListPostListItem,
} from "../streamHubAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * PUBLISHED 게시글 목록(검색·페이지네이션).
 * @summary 공개 게시글 목록
 */
export const publicPosts = (
  params?: PublicPostsParams,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOResInfinityListPostListItem>({
    url: `/pub/v1/posts`,
    method: "GET",
    params,
    signal,
  });
};

export const getPublicPostsQueryKey = (params?: PublicPostsParams) => {
  return [`/pub/v1/posts`, ...(params ? [params] : [])] as const;
};

export const getPublicPostsQueryOptions = <
  TData = Awaited<ReturnType<typeof publicPosts>>,
  TError = unknown
>(
  params?: PublicPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicPosts>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPublicPostsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof publicPosts>>> = ({
    signal,
  }) => publicPosts(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof publicPosts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PublicPostsQueryResult = NonNullable<
  Awaited<ReturnType<typeof publicPosts>>
>;
export type PublicPostsQueryError = unknown;

export function usePublicPosts<
  TData = Awaited<ReturnType<typeof publicPosts>>,
  TError = unknown
>(
  params: undefined | PublicPostsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicPosts>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicPosts>>,
          TError,
          Awaited<ReturnType<typeof publicPosts>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicPosts<
  TData = Awaited<ReturnType<typeof publicPosts>>,
  TError = unknown
>(
  params?: PublicPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicPosts>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicPosts>>,
          TError,
          Awaited<ReturnType<typeof publicPosts>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicPosts<
  TData = Awaited<ReturnType<typeof publicPosts>>,
  TError = unknown
>(
  params?: PublicPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicPosts>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 공개 게시글 목록
 */

export function usePublicPosts<
  TData = Awaited<ReturnType<typeof publicPosts>>,
  TError = unknown
>(
  params?: PublicPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicPosts>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPublicPostsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 공개 게시글 상세
 */
export const publicPostsDetail = (id: number, signal?: AbortSignal) => {
  return customInstance<ResultDTOPostDetail>({
    url: `/pub/v1/posts/${id}`,
    method: "GET",
    signal,
  });
};

export const getPublicPostsDetailQueryKey = (id?: number) => {
  return [`/pub/v1/posts/${id}`] as const;
};

export const getPublicPostsDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof publicPostsDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicPostsDetail>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPublicPostsDetailQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof publicPostsDetail>>
  > = ({ signal }) => publicPostsDetail(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof publicPostsDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PublicPostsDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof publicPostsDetail>>
>;
export type PublicPostsDetailQueryError = unknown;

export function usePublicPostsDetail<
  TData = Awaited<ReturnType<typeof publicPostsDetail>>,
  TError = unknown
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicPostsDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicPostsDetail>>,
          TError,
          Awaited<ReturnType<typeof publicPostsDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicPostsDetail<
  TData = Awaited<ReturnType<typeof publicPostsDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicPostsDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicPostsDetail>>,
          TError,
          Awaited<ReturnType<typeof publicPostsDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicPostsDetail<
  TData = Awaited<ReturnType<typeof publicPostsDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicPostsDetail>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 공개 게시글 상세
 */

export function usePublicPostsDetail<
  TData = Awaited<ReturnType<typeof publicPostsDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicPostsDetail>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPublicPostsDetailQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 최신 영상/음악/게시글을 한 번에 반환.
 * @summary 홈 묶음
 */
export const publicHome = (signal?: AbortSignal) => {
  return customInstance<ResultDTOPublicHomeResponse>({
    url: `/pub/v1/home`,
    method: "GET",
    signal,
  });
};

export const getPublicHomeQueryKey = () => {
  return [`/pub/v1/home`] as const;
};

export const getPublicHomeQueryOptions = <
  TData = Awaited<ReturnType<typeof publicHome>>,
  TError = unknown
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof publicHome>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPublicHomeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof publicHome>>> = ({
    signal,
  }) => publicHome(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof publicHome>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PublicHomeQueryResult = NonNullable<
  Awaited<ReturnType<typeof publicHome>>
>;
export type PublicHomeQueryError = unknown;

export function usePublicHome<
  TData = Awaited<ReturnType<typeof publicHome>>,
  TError = unknown
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicHome>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicHome>>,
          TError,
          Awaited<ReturnType<typeof publicHome>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicHome<
  TData = Awaited<ReturnType<typeof publicHome>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicHome>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicHome>>,
          TError,
          Awaited<ReturnType<typeof publicHome>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicHome<
  TData = Awaited<ReturnType<typeof publicHome>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicHome>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 홈 묶음
 */

export function usePublicHome<
  TData = Awaited<ReturnType<typeof publicHome>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicHome>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPublicHomeQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * PUBLISHED 영상/음악 목록(검색·페이지네이션).
 * @summary 공개 콘텐츠 목록
 */
export const publicContents = (
  params?: PublicContentsParams,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOResInfinityListContentListItem>({
    url: `/pub/v1/contents`,
    method: "GET",
    params,
    signal,
  });
};

export const getPublicContentsQueryKey = (params?: PublicContentsParams) => {
  return [`/pub/v1/contents`, ...(params ? [params] : [])] as const;
};

export const getPublicContentsQueryOptions = <
  TData = Awaited<ReturnType<typeof publicContents>>,
  TError = unknown
>(
  params?: PublicContentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicContents>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPublicContentsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof publicContents>>> = ({
    signal,
  }) => publicContents(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof publicContents>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PublicContentsQueryResult = NonNullable<
  Awaited<ReturnType<typeof publicContents>>
>;
export type PublicContentsQueryError = unknown;

export function usePublicContents<
  TData = Awaited<ReturnType<typeof publicContents>>,
  TError = unknown
>(
  params: undefined | PublicContentsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicContents>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicContents>>,
          TError,
          Awaited<ReturnType<typeof publicContents>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicContents<
  TData = Awaited<ReturnType<typeof publicContents>>,
  TError = unknown
>(
  params?: PublicContentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicContents>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicContents>>,
          TError,
          Awaited<ReturnType<typeof publicContents>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicContents<
  TData = Awaited<ReturnType<typeof publicContents>>,
  TError = unknown
>(
  params?: PublicContentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicContents>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 공개 콘텐츠 목록
 */

export function usePublicContents<
  TData = Awaited<ReturnType<typeof publicContents>>,
  TError = unknown
>(
  params?: PublicContentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicContents>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPublicContentsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * PUBLISHED만 반환하며 조회수를 1 증가시킨다.
 * @summary 공개 콘텐츠 상세
 */
export const publicContentsDetail = (id: number, signal?: AbortSignal) => {
  return customInstance<ResultDTOContentDetail>({
    url: `/pub/v1/contents/${id}`,
    method: "GET",
    signal,
  });
};

export const getPublicContentsDetailQueryKey = (id?: number) => {
  return [`/pub/v1/contents/${id}`] as const;
};

export const getPublicContentsDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof publicContentsDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicContentsDetail>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getPublicContentsDetailQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof publicContentsDetail>>
  > = ({ signal }) => publicContentsDetail(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof publicContentsDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PublicContentsDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof publicContentsDetail>>
>;
export type PublicContentsDetailQueryError = unknown;

export function usePublicContentsDetail<
  TData = Awaited<ReturnType<typeof publicContentsDetail>>,
  TError = unknown
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicContentsDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicContentsDetail>>,
          TError,
          Awaited<ReturnType<typeof publicContentsDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicContentsDetail<
  TData = Awaited<ReturnType<typeof publicContentsDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicContentsDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicContentsDetail>>,
          TError,
          Awaited<ReturnType<typeof publicContentsDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicContentsDetail<
  TData = Awaited<ReturnType<typeof publicContentsDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicContentsDetail>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 공개 콘텐츠 상세
 */

export function usePublicContentsDetail<
  TData = Awaited<ReturnType<typeof publicContentsDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicContentsDetail>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPublicContentsDetailQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
