/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * GraceOn Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  PublicAlbumsParams,
  PublicBannersParams,
  PublicChannelsParams,
  PublicChurchesParams,
  PublicContentsParams,
  PublicPostsParams,
  PublicStoresParams,
  ResultDTOAlbumDetail,
  ResultDTOListAnnouncementDto,
  ResultDTOListBannerDto,
  ResultDTOListPlaylistDto,
  ResultDTOListPublicChannelItem,
  ResultDTOListStoreDto,
  ResultDTOPlaylistDetail,
  ResultDTOPostDetail,
  ResultDTOPreviewResponse,
  ResultDTOPublicChurchDetail,
  ResultDTOPublicContentDetail,
  ResultDTOPublicHomeResponse,
  ResultDTOResInfinityListAlbumListItem,
  ResultDTOResInfinityListChurchNearbyItem,
  ResultDTOResInfinityListContentListItem,
  ResultDTOResInfinityListPostListItem,
  ResultDTOVoid,
} from "../graceOnAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * 공개 사이트에서 콘텐츠 접속 시마다 호출 — 접속자 누구든 조회수를 1 증가시킨다(중복 제거 없음).
 * @summary 콘텐츠 조회수 +1
 */
export const publicContentsViewCreate = (id: number, signal?: AbortSignal) => {
  return customInstance<ResultDTOVoid>({
    url: `/pub/v1/contents/${id}/view`,
    method: "POST",
    signal,
  });
};

export const getPublicContentsViewCreateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof publicContentsViewCreate>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof publicContentsViewCreate>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["publicContentsViewCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof publicContentsViewCreate>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return publicContentsViewCreate(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type PublicContentsViewCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof publicContentsViewCreate>>
>;

export type PublicContentsViewCreateMutationError = unknown;

/**
 * @summary 콘텐츠 조회수 +1
 */
export const usePublicContentsViewCreate = <
  TError = unknown,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof publicContentsViewCreate>>,
      TError,
      { id: number },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof publicContentsViewCreate>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getPublicContentsViewCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 현위치(lat/lng) 기준 거리순. 좌표 미제공 시 지역 필터만 적용. 데모 가상 매장.
 * @summary 공개 매장찾기
 */
export const publicStores = (
  params?: PublicStoresParams,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOListStoreDto>({
    url: `/pub/v1/stores`,
    method: "GET",
    params,
    signal,
  });
};

export const getPublicStoresQueryKey = (params?: PublicStoresParams) => {
  return [`/pub/v1/stores`, ...(params ? [params] : [])] as const;
};

export const getPublicStoresQueryOptions = <
  TData = Awaited<ReturnType<typeof publicStores>>,
  TError = unknown
>(
  params?: PublicStoresParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicStores>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPublicStoresQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof publicStores>>> = ({
    signal,
  }) => publicStores(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof publicStores>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PublicStoresQueryResult = NonNullable<
  Awaited<ReturnType<typeof publicStores>>
>;
export type PublicStoresQueryError = unknown;

export function usePublicStores<
  TData = Awaited<ReturnType<typeof publicStores>>,
  TError = unknown
>(
  params: undefined | PublicStoresParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicStores>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicStores>>,
          TError,
          Awaited<ReturnType<typeof publicStores>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicStores<
  TData = Awaited<ReturnType<typeof publicStores>>,
  TError = unknown
>(
  params?: PublicStoresParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicStores>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicStores>>,
          TError,
          Awaited<ReturnType<typeof publicStores>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicStores<
  TData = Awaited<ReturnType<typeof publicStores>>,
  TError = unknown
>(
  params?: PublicStoresParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicStores>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 공개 매장찾기
 */

export function usePublicStores<
  TData = Awaited<ReturnType<typeof publicStores>>,
  TError = unknown
>(
  params?: PublicStoresParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicStores>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPublicStoresQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * PUBLISHED 게시글 목록(검색·페이지네이션).
 * @summary 공개 게시글 목록
 */
export const publicPosts = (
  params?: PublicPostsParams,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOResInfinityListPostListItem>({
    url: `/pub/v1/posts`,
    method: "GET",
    params,
    signal,
  });
};

export const getPublicPostsQueryKey = (params?: PublicPostsParams) => {
  return [`/pub/v1/posts`, ...(params ? [params] : [])] as const;
};

export const getPublicPostsQueryOptions = <
  TData = Awaited<ReturnType<typeof publicPosts>>,
  TError = unknown
>(
  params?: PublicPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicPosts>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPublicPostsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof publicPosts>>> = ({
    signal,
  }) => publicPosts(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof publicPosts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PublicPostsQueryResult = NonNullable<
  Awaited<ReturnType<typeof publicPosts>>
>;
export type PublicPostsQueryError = unknown;

export function usePublicPosts<
  TData = Awaited<ReturnType<typeof publicPosts>>,
  TError = unknown
>(
  params: undefined | PublicPostsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicPosts>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicPosts>>,
          TError,
          Awaited<ReturnType<typeof publicPosts>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicPosts<
  TData = Awaited<ReturnType<typeof publicPosts>>,
  TError = unknown
>(
  params?: PublicPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicPosts>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicPosts>>,
          TError,
          Awaited<ReturnType<typeof publicPosts>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicPosts<
  TData = Awaited<ReturnType<typeof publicPosts>>,
  TError = unknown
>(
  params?: PublicPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicPosts>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 공개 게시글 목록
 */

export function usePublicPosts<
  TData = Awaited<ReturnType<typeof publicPosts>>,
  TError = unknown
>(
  params?: PublicPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicPosts>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPublicPostsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 공개 게시글 상세
 */
export const publicPostsDetail = (id: number, signal?: AbortSignal) => {
  return customInstance<ResultDTOPostDetail>({
    url: `/pub/v1/posts/${id}`,
    method: "GET",
    signal,
  });
};

export const getPublicPostsDetailQueryKey = (id?: number) => {
  return [`/pub/v1/posts/${id}`] as const;
};

export const getPublicPostsDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof publicPostsDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicPostsDetail>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPublicPostsDetailQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof publicPostsDetail>>
  > = ({ signal }) => publicPostsDetail(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof publicPostsDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PublicPostsDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof publicPostsDetail>>
>;
export type PublicPostsDetailQueryError = unknown;

export function usePublicPostsDetail<
  TData = Awaited<ReturnType<typeof publicPostsDetail>>,
  TError = unknown
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicPostsDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicPostsDetail>>,
          TError,
          Awaited<ReturnType<typeof publicPostsDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicPostsDetail<
  TData = Awaited<ReturnType<typeof publicPostsDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicPostsDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicPostsDetail>>,
          TError,
          Awaited<ReturnType<typeof publicPostsDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicPostsDetail<
  TData = Awaited<ReturnType<typeof publicPostsDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicPostsDetail>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 공개 게시글 상세
 */

export function usePublicPostsDetail<
  TData = Awaited<ReturnType<typeof publicPostsDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicPostsDetail>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPublicPostsDetailQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 노출(use_yn=Y) 플레이리스트를 정렬순으로 반환.
 * @summary 공개 플레이리스트 목록
 */
export const publicPlaylists = (signal?: AbortSignal) => {
  return customInstance<ResultDTOListPlaylistDto>({
    url: `/pub/v1/playlists`,
    method: "GET",
    signal,
  });
};

export const getPublicPlaylistsQueryKey = () => {
  return [`/pub/v1/playlists`] as const;
};

export const getPublicPlaylistsQueryOptions = <
  TData = Awaited<ReturnType<typeof publicPlaylists>>,
  TError = unknown
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof publicPlaylists>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPublicPlaylistsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof publicPlaylists>>> = ({
    signal,
  }) => publicPlaylists(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof publicPlaylists>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PublicPlaylistsQueryResult = NonNullable<
  Awaited<ReturnType<typeof publicPlaylists>>
>;
export type PublicPlaylistsQueryError = unknown;

export function usePublicPlaylists<
  TData = Awaited<ReturnType<typeof publicPlaylists>>,
  TError = unknown
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicPlaylists>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicPlaylists>>,
          TError,
          Awaited<ReturnType<typeof publicPlaylists>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicPlaylists<
  TData = Awaited<ReturnType<typeof publicPlaylists>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicPlaylists>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicPlaylists>>,
          TError,
          Awaited<ReturnType<typeof publicPlaylists>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicPlaylists<
  TData = Awaited<ReturnType<typeof publicPlaylists>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicPlaylists>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 공개 플레이리스트 목록
 */

export function usePublicPlaylists<
  TData = Awaited<ReturnType<typeof publicPlaylists>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicPlaylists>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPublicPlaylistsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 수록 트랙 포함(전곡 무료 재생).
 * @summary 공개 플레이리스트 상세
 */
export const publicPlaylistsDetail = (id: number, signal?: AbortSignal) => {
  return customInstance<ResultDTOPlaylistDetail>({
    url: `/pub/v1/playlists/${id}`,
    method: "GET",
    signal,
  });
};

export const getPublicPlaylistsDetailQueryKey = (id?: number) => {
  return [`/pub/v1/playlists/${id}`] as const;
};

export const getPublicPlaylistsDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof publicPlaylistsDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicPlaylistsDetail>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getPublicPlaylistsDetailQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof publicPlaylistsDetail>>
  > = ({ signal }) => publicPlaylistsDetail(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof publicPlaylistsDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PublicPlaylistsDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof publicPlaylistsDetail>>
>;
export type PublicPlaylistsDetailQueryError = unknown;

export function usePublicPlaylistsDetail<
  TData = Awaited<ReturnType<typeof publicPlaylistsDetail>>,
  TError = unknown
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicPlaylistsDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicPlaylistsDetail>>,
          TError,
          Awaited<ReturnType<typeof publicPlaylistsDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicPlaylistsDetail<
  TData = Awaited<ReturnType<typeof publicPlaylistsDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicPlaylistsDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicPlaylistsDetail>>,
          TError,
          Awaited<ReturnType<typeof publicPlaylistsDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicPlaylistsDetail<
  TData = Awaited<ReturnType<typeof publicPlaylistsDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicPlaylistsDetail>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 공개 플레이리스트 상세
 */

export function usePublicPlaylistsDetail<
  TData = Awaited<ReturnType<typeof publicPlaylistsDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicPlaylistsDetail>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPublicPlaylistsDetailQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 최신 영상/음악/게시글을 한 번에 반환.
 * @summary 홈 묶음
 */
export const publicHome = (signal?: AbortSignal) => {
  return customInstance<ResultDTOPublicHomeResponse>({
    url: `/pub/v1/home`,
    method: "GET",
    signal,
  });
};

export const getPublicHomeQueryKey = () => {
  return [`/pub/v1/home`] as const;
};

export const getPublicHomeQueryOptions = <
  TData = Awaited<ReturnType<typeof publicHome>>,
  TError = unknown
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof publicHome>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPublicHomeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof publicHome>>> = ({
    signal,
  }) => publicHome(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof publicHome>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PublicHomeQueryResult = NonNullable<
  Awaited<ReturnType<typeof publicHome>>
>;
export type PublicHomeQueryError = unknown;

export function usePublicHome<
  TData = Awaited<ReturnType<typeof publicHome>>,
  TError = unknown
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicHome>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicHome>>,
          TError,
          Awaited<ReturnType<typeof publicHome>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicHome<
  TData = Awaited<ReturnType<typeof publicHome>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicHome>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicHome>>,
          TError,
          Awaited<ReturnType<typeof publicHome>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicHome<
  TData = Awaited<ReturnType<typeof publicHome>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicHome>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 홈 묶음
 */

export function usePublicHome<
  TData = Awaited<ReturnType<typeof publicHome>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicHome>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPublicHomeQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * PUBLISHED 영상/음악 목록(검색·채널 필터·페이지네이션·정렬).
 * @summary 공개 콘텐츠 목록
 */
export const publicContents = (
  params?: PublicContentsParams,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOResInfinityListContentListItem>({
    url: `/pub/v1/contents`,
    method: "GET",
    params,
    signal,
  });
};

export const getPublicContentsQueryKey = (params?: PublicContentsParams) => {
  return [`/pub/v1/contents`, ...(params ? [params] : [])] as const;
};

export const getPublicContentsQueryOptions = <
  TData = Awaited<ReturnType<typeof publicContents>>,
  TError = unknown
>(
  params?: PublicContentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicContents>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPublicContentsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof publicContents>>> = ({
    signal,
  }) => publicContents(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof publicContents>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PublicContentsQueryResult = NonNullable<
  Awaited<ReturnType<typeof publicContents>>
>;
export type PublicContentsQueryError = unknown;

export function usePublicContents<
  TData = Awaited<ReturnType<typeof publicContents>>,
  TError = unknown
>(
  params: undefined | PublicContentsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicContents>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicContents>>,
          TError,
          Awaited<ReturnType<typeof publicContents>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicContents<
  TData = Awaited<ReturnType<typeof publicContents>>,
  TError = unknown
>(
  params?: PublicContentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicContents>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicContents>>,
          TError,
          Awaited<ReturnType<typeof publicContents>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicContents<
  TData = Awaited<ReturnType<typeof publicContents>>,
  TError = unknown
>(
  params?: PublicContentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicContents>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 공개 콘텐츠 목록
 */

export function usePublicContents<
  TData = Awaited<ReturnType<typeof publicContents>>,
  TError = unknown
>(
  params?: PublicContentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicContents>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPublicContentsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * PUBLISHED만 반환하며 조회수를 1 증가시킨다.
 * @summary 공개 콘텐츠 상세
 */
export const publicContentsDetail = (id: number, signal?: AbortSignal) => {
  return customInstance<ResultDTOPublicContentDetail>({
    url: `/pub/v1/contents/${id}`,
    method: "GET",
    signal,
  });
};

export const getPublicContentsDetailQueryKey = (id?: number) => {
  return [`/pub/v1/contents/${id}`] as const;
};

export const getPublicContentsDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof publicContentsDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicContentsDetail>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getPublicContentsDetailQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof publicContentsDetail>>
  > = ({ signal }) => publicContentsDetail(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof publicContentsDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PublicContentsDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof publicContentsDetail>>
>;
export type PublicContentsDetailQueryError = unknown;

export function usePublicContentsDetail<
  TData = Awaited<ReturnType<typeof publicContentsDetail>>,
  TError = unknown
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicContentsDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicContentsDetail>>,
          TError,
          Awaited<ReturnType<typeof publicContentsDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicContentsDetail<
  TData = Awaited<ReturnType<typeof publicContentsDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicContentsDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicContentsDetail>>,
          TError,
          Awaited<ReturnType<typeof publicContentsDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicContentsDetail<
  TData = Awaited<ReturnType<typeof publicContentsDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicContentsDetail>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 공개 콘텐츠 상세
 */

export function usePublicContentsDetail<
  TData = Awaited<ReturnType<typeof publicContentsDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicContentsDetail>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPublicContentsDetailQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 현위치(lat/lng) 기준 거리순. 좌표 미제공 시 지역/교단/키워드 필터만 적용. 과도한 요청은 429.
 * @summary 교회 위치검색
 */
export const publicChurches = (
  params?: PublicChurchesParams,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOResInfinityListChurchNearbyItem>({
    url: `/pub/v1/churches`,
    method: "GET",
    params,
    signal,
  });
};

export const getPublicChurchesQueryKey = (params?: PublicChurchesParams) => {
  return [`/pub/v1/churches`, ...(params ? [params] : [])] as const;
};

export const getPublicChurchesQueryOptions = <
  TData = Awaited<ReturnType<typeof publicChurches>>,
  TError = unknown
>(
  params?: PublicChurchesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicChurches>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPublicChurchesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof publicChurches>>> = ({
    signal,
  }) => publicChurches(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof publicChurches>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PublicChurchesQueryResult = NonNullable<
  Awaited<ReturnType<typeof publicChurches>>
>;
export type PublicChurchesQueryError = unknown;

export function usePublicChurches<
  TData = Awaited<ReturnType<typeof publicChurches>>,
  TError = unknown
>(
  params: undefined | PublicChurchesParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicChurches>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicChurches>>,
          TError,
          Awaited<ReturnType<typeof publicChurches>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicChurches<
  TData = Awaited<ReturnType<typeof publicChurches>>,
  TError = unknown
>(
  params?: PublicChurchesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicChurches>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicChurches>>,
          TError,
          Awaited<ReturnType<typeof publicChurches>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicChurches<
  TData = Awaited<ReturnType<typeof publicChurches>>,
  TError = unknown
>(
  params?: PublicChurchesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicChurches>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 교회 위치검색
 */

export function usePublicChurches<
  TData = Awaited<ReturnType<typeof publicChurches>>,
  TError = unknown
>(
  params?: PublicChurchesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicChurches>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPublicChurchesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 노출(use_yn=Y) 교회만 반환하며 예배시간을 포함한다.
 * @summary 공개 교회 상세
 */
export const publicChurchesDetail = (id: number, signal?: AbortSignal) => {
  return customInstance<ResultDTOPublicChurchDetail>({
    url: `/pub/v1/churches/${id}`,
    method: "GET",
    signal,
  });
};

export const getPublicChurchesDetailQueryKey = (id?: number) => {
  return [`/pub/v1/churches/${id}`] as const;
};

export const getPublicChurchesDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof publicChurchesDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicChurchesDetail>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getPublicChurchesDetailQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof publicChurchesDetail>>
  > = ({ signal }) => publicChurchesDetail(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof publicChurchesDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PublicChurchesDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof publicChurchesDetail>>
>;
export type PublicChurchesDetailQueryError = unknown;

export function usePublicChurchesDetail<
  TData = Awaited<ReturnType<typeof publicChurchesDetail>>,
  TError = unknown
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicChurchesDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicChurchesDetail>>,
          TError,
          Awaited<ReturnType<typeof publicChurchesDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicChurchesDetail<
  TData = Awaited<ReturnType<typeof publicChurchesDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicChurchesDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicChurchesDetail>>,
          TError,
          Awaited<ReturnType<typeof publicChurchesDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicChurchesDetail<
  TData = Awaited<ReturnType<typeof publicChurchesDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicChurchesDetail>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 공개 교회 상세
 */

export function usePublicChurchesDetail<
  TData = Awaited<ReturnType<typeof publicChurchesDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicChurchesDetail>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPublicChurchesDetailQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * PUBLISHED 콘텐츠를 가진 채널을 활동순으로 반환(type=VIDEO/SOUND). 채널 브라우징용.
 * @summary 공개 채널 목록
 */
export const publicChannels = (
  params?: PublicChannelsParams,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOListPublicChannelItem>({
    url: `/pub/v1/channels`,
    method: "GET",
    params,
    signal,
  });
};

export const getPublicChannelsQueryKey = (params?: PublicChannelsParams) => {
  return [`/pub/v1/channels`, ...(params ? [params] : [])] as const;
};

export const getPublicChannelsQueryOptions = <
  TData = Awaited<ReturnType<typeof publicChannels>>,
  TError = unknown
>(
  params?: PublicChannelsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicChannels>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPublicChannelsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof publicChannels>>> = ({
    signal,
  }) => publicChannels(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof publicChannels>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PublicChannelsQueryResult = NonNullable<
  Awaited<ReturnType<typeof publicChannels>>
>;
export type PublicChannelsQueryError = unknown;

export function usePublicChannels<
  TData = Awaited<ReturnType<typeof publicChannels>>,
  TError = unknown
>(
  params: undefined | PublicChannelsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicChannels>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicChannels>>,
          TError,
          Awaited<ReturnType<typeof publicChannels>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicChannels<
  TData = Awaited<ReturnType<typeof publicChannels>>,
  TError = unknown
>(
  params?: PublicChannelsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicChannels>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicChannels>>,
          TError,
          Awaited<ReturnType<typeof publicChannels>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicChannels<
  TData = Awaited<ReturnType<typeof publicChannels>>,
  TError = unknown
>(
  params?: PublicChannelsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicChannels>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 공개 채널 목록
 */

export function usePublicChannels<
  TData = Awaited<ReturnType<typeof publicChannels>>,
  TError = unknown
>(
  params?: PublicChannelsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicChannels>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPublicChannelsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 노출 중인 탭 배너(target=VIDEO/SOUND, ALL 포함). 정렬순.
 * @summary 공개 배너 목록
 */
export const publicBanners = (
  params?: PublicBannersParams,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOListBannerDto>({
    url: `/pub/v1/banners`,
    method: "GET",
    params,
    signal,
  });
};

export const getPublicBannersQueryKey = (params?: PublicBannersParams) => {
  return [`/pub/v1/banners`, ...(params ? [params] : [])] as const;
};

export const getPublicBannersQueryOptions = <
  TData = Awaited<ReturnType<typeof publicBanners>>,
  TError = unknown
>(
  params?: PublicBannersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicBanners>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPublicBannersQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof publicBanners>>> = ({
    signal,
  }) => publicBanners(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof publicBanners>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PublicBannersQueryResult = NonNullable<
  Awaited<ReturnType<typeof publicBanners>>
>;
export type PublicBannersQueryError = unknown;

export function usePublicBanners<
  TData = Awaited<ReturnType<typeof publicBanners>>,
  TError = unknown
>(
  params: undefined | PublicBannersParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicBanners>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicBanners>>,
          TError,
          Awaited<ReturnType<typeof publicBanners>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicBanners<
  TData = Awaited<ReturnType<typeof publicBanners>>,
  TError = unknown
>(
  params?: PublicBannersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicBanners>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicBanners>>,
          TError,
          Awaited<ReturnType<typeof publicBanners>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicBanners<
  TData = Awaited<ReturnType<typeof publicBanners>>,
  TError = unknown
>(
  params?: PublicBannersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicBanners>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 공개 배너 목록
 */

export function usePublicBanners<
  TData = Awaited<ReturnType<typeof publicBanners>>,
  TError = unknown
>(
  params?: PublicBannersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicBanners>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPublicBannersQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 노출 중인 안내창(모달 광고) 목록. 노출여부·기간으로 필터, 정렬순.
 * @summary 공개 안내창
 */
export const publicAnnouncement = (signal?: AbortSignal) => {
  return customInstance<ResultDTOListAnnouncementDto>({
    url: `/pub/v1/announcement`,
    method: "GET",
    signal,
  });
};

export const getPublicAnnouncementQueryKey = () => {
  return [`/pub/v1/announcement`] as const;
};

export const getPublicAnnouncementQueryOptions = <
  TData = Awaited<ReturnType<typeof publicAnnouncement>>,
  TError = unknown
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof publicAnnouncement>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPublicAnnouncementQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof publicAnnouncement>>
  > = ({ signal }) => publicAnnouncement(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof publicAnnouncement>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PublicAnnouncementQueryResult = NonNullable<
  Awaited<ReturnType<typeof publicAnnouncement>>
>;
export type PublicAnnouncementQueryError = unknown;

export function usePublicAnnouncement<
  TData = Awaited<ReturnType<typeof publicAnnouncement>>,
  TError = unknown
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicAnnouncement>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicAnnouncement>>,
          TError,
          Awaited<ReturnType<typeof publicAnnouncement>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicAnnouncement<
  TData = Awaited<ReturnType<typeof publicAnnouncement>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicAnnouncement>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicAnnouncement>>,
          TError,
          Awaited<ReturnType<typeof publicAnnouncement>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicAnnouncement<
  TData = Awaited<ReturnType<typeof publicAnnouncement>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicAnnouncement>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 공개 안내창
 */

export function usePublicAnnouncement<
  TData = Awaited<ReturnType<typeof publicAnnouncement>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicAnnouncement>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPublicAnnouncementQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * ON_SALE 음반 목록(장르 필터·검색·페이지네이션·정렬). sortBy=viewCount(인기)/releaseDate(최신)/createdAt 등, sortDir=asc/desc.
 * @summary 공개 앨범 목록
 */
export const publicAlbums = (
  params?: PublicAlbumsParams,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOResInfinityListAlbumListItem>({
    url: `/pub/v1/albums`,
    method: "GET",
    params,
    signal,
  });
};

export const getPublicAlbumsQueryKey = (params?: PublicAlbumsParams) => {
  return [`/pub/v1/albums`, ...(params ? [params] : [])] as const;
};

export const getPublicAlbumsQueryOptions = <
  TData = Awaited<ReturnType<typeof publicAlbums>>,
  TError = unknown
>(
  params?: PublicAlbumsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicAlbums>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPublicAlbumsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof publicAlbums>>> = ({
    signal,
  }) => publicAlbums(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof publicAlbums>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PublicAlbumsQueryResult = NonNullable<
  Awaited<ReturnType<typeof publicAlbums>>
>;
export type PublicAlbumsQueryError = unknown;

export function usePublicAlbums<
  TData = Awaited<ReturnType<typeof publicAlbums>>,
  TError = unknown
>(
  params: undefined | PublicAlbumsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicAlbums>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicAlbums>>,
          TError,
          Awaited<ReturnType<typeof publicAlbums>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicAlbums<
  TData = Awaited<ReturnType<typeof publicAlbums>>,
  TError = unknown
>(
  params?: PublicAlbumsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicAlbums>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicAlbums>>,
          TError,
          Awaited<ReturnType<typeof publicAlbums>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicAlbums<
  TData = Awaited<ReturnType<typeof publicAlbums>>,
  TError = unknown
>(
  params?: PublicAlbumsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicAlbums>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 공개 앨범 목록
 */

export function usePublicAlbums<
  TData = Awaited<ReturnType<typeof publicAlbums>>,
  TError = unknown
>(
  params?: PublicAlbumsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof publicAlbums>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPublicAlbumsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * ON_SALE만 반환하며 트랙리스트를 포함하고 조회수를 1 증가시킨다.
 * @summary 공개 앨범 상세
 */
export const publicAlbumsDetail = (id: number, signal?: AbortSignal) => {
  return customInstance<ResultDTOAlbumDetail>({
    url: `/pub/v1/albums/${id}`,
    method: "GET",
    signal,
  });
};

export const getPublicAlbumsDetailQueryKey = (id?: number) => {
  return [`/pub/v1/albums/${id}`] as const;
};

export const getPublicAlbumsDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof publicAlbumsDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicAlbumsDetail>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPublicAlbumsDetailQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof publicAlbumsDetail>>
  > = ({ signal }) => publicAlbumsDetail(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof publicAlbumsDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PublicAlbumsDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof publicAlbumsDetail>>
>;
export type PublicAlbumsDetailQueryError = unknown;

export function usePublicAlbumsDetail<
  TData = Awaited<ReturnType<typeof publicAlbumsDetail>>,
  TError = unknown
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicAlbumsDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicAlbumsDetail>>,
          TError,
          Awaited<ReturnType<typeof publicAlbumsDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicAlbumsDetail<
  TData = Awaited<ReturnType<typeof publicAlbumsDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicAlbumsDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicAlbumsDetail>>,
          TError,
          Awaited<ReturnType<typeof publicAlbumsDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicAlbumsDetail<
  TData = Awaited<ReturnType<typeof publicAlbumsDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicAlbumsDetail>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 공개 앨범 상세
 */

export function usePublicAlbumsDetail<
  TData = Awaited<ReturnType<typeof publicAlbumsDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicAlbumsDetail>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPublicAlbumsDetailQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 30초 미리듣기 음원 URL·구간·데모 플래그를 반환한다.
 * @summary 트랙 미리듣기
 */
export const publicAlbumsTracksPreview = (
  albumId: number,
  trackId: number,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOPreviewResponse>({
    url: `/pub/v1/albums/${albumId}/tracks/${trackId}/preview`,
    method: "GET",
    signal,
  });
};

export const getPublicAlbumsTracksPreviewQueryKey = (
  albumId?: number,
  trackId?: number
) => {
  return [`/pub/v1/albums/${albumId}/tracks/${trackId}/preview`] as const;
};

export const getPublicAlbumsTracksPreviewQueryOptions = <
  TData = Awaited<ReturnType<typeof publicAlbumsTracksPreview>>,
  TError = unknown
>(
  albumId: number,
  trackId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicAlbumsTracksPreview>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getPublicAlbumsTracksPreviewQueryKey(albumId, trackId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof publicAlbumsTracksPreview>>
  > = ({ signal }) => publicAlbumsTracksPreview(albumId, trackId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(albumId && trackId),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof publicAlbumsTracksPreview>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PublicAlbumsTracksPreviewQueryResult = NonNullable<
  Awaited<ReturnType<typeof publicAlbumsTracksPreview>>
>;
export type PublicAlbumsTracksPreviewQueryError = unknown;

export function usePublicAlbumsTracksPreview<
  TData = Awaited<ReturnType<typeof publicAlbumsTracksPreview>>,
  TError = unknown
>(
  albumId: number,
  trackId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicAlbumsTracksPreview>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicAlbumsTracksPreview>>,
          TError,
          Awaited<ReturnType<typeof publicAlbumsTracksPreview>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicAlbumsTracksPreview<
  TData = Awaited<ReturnType<typeof publicAlbumsTracksPreview>>,
  TError = unknown
>(
  albumId: number,
  trackId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicAlbumsTracksPreview>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicAlbumsTracksPreview>>,
          TError,
          Awaited<ReturnType<typeof publicAlbumsTracksPreview>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicAlbumsTracksPreview<
  TData = Awaited<ReturnType<typeof publicAlbumsTracksPreview>>,
  TError = unknown
>(
  albumId: number,
  trackId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicAlbumsTracksPreview>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 트랙 미리듣기
 */

export function usePublicAlbumsTracksPreview<
  TData = Awaited<ReturnType<typeof publicAlbumsTracksPreview>>,
  TError = unknown
>(
  albumId: number,
  trackId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicAlbumsTracksPreview>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPublicAlbumsTracksPreviewQueryOptions(
    albumId,
    trackId,
    options
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
