/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * GraceOn Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type {
  GoodsCategorySaveRequest,
  ResultDTOGoodsCategoryNodeDto,
  ResultDTOListGoodsCategoryNodeDto,
  ResultDTOVoid,
} from "../graceOnAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * 이름/정렬순서/사용여부를 수정한다.
 * @summary 카테고리 수정
 */
export const goodsCategoryUpdate = (
  id: number,
  goodsCategorySaveRequest: GoodsCategorySaveRequest
) => {
  return customInstance<ResultDTOGoodsCategoryNodeDto>({
    url: `/v1/goods-category/${id}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: goodsCategorySaveRequest,
  });
};

export const getGoodsCategoryUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof goodsCategoryUpdate>>,
    TError,
    { id: number; data: GoodsCategorySaveRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof goodsCategoryUpdate>>,
  TError,
  { id: number; data: GoodsCategorySaveRequest },
  TContext
> => {
  const mutationKey = ["goodsCategoryUpdate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof goodsCategoryUpdate>>,
    { id: number; data: GoodsCategorySaveRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return goodsCategoryUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type GoodsCategoryUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof goodsCategoryUpdate>>
>;
export type GoodsCategoryUpdateMutationBody = GoodsCategorySaveRequest;
export type GoodsCategoryUpdateMutationError = unknown;

/**
 * @summary 카테고리 수정
 */
export const useGoodsCategoryUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof goodsCategoryUpdate>>,
      TError,
      { id: number; data: GoodsCategorySaveRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof goodsCategoryUpdate>>,
  TError,
  { id: number; data: GoodsCategorySaveRequest },
  TContext
> => {
  const mutationOptions = getGoodsCategoryUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 카테고리 삭제
 */
export const goodsCategoryDelete = (id: number) => {
  return customInstance<ResultDTOVoid>({
    url: `/v1/goods-category/${id}`,
    method: "DELETE",
  });
};

export const getGoodsCategoryDeleteMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof goodsCategoryDelete>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof goodsCategoryDelete>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["goodsCategoryDelete"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof goodsCategoryDelete>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return goodsCategoryDelete(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type GoodsCategoryDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof goodsCategoryDelete>>
>;

export type GoodsCategoryDeleteMutationError = unknown;

/**
 * @summary 카테고리 삭제
 */
export const useGoodsCategoryDelete = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof goodsCategoryDelete>>,
      TError,
      { id: number },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof goodsCategoryDelete>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getGoodsCategoryDeleteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 카테고리 등록
 */
export const goodsCategoryCreate = (
  goodsCategorySaveRequest: GoodsCategorySaveRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOGoodsCategoryNodeDto>({
    url: `/v1/goods-category`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: goodsCategorySaveRequest,
    signal,
  });
};

export const getGoodsCategoryCreateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof goodsCategoryCreate>>,
    TError,
    { data: GoodsCategorySaveRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof goodsCategoryCreate>>,
  TError,
  { data: GoodsCategorySaveRequest },
  TContext
> => {
  const mutationKey = ["goodsCategoryCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof goodsCategoryCreate>>,
    { data: GoodsCategorySaveRequest }
  > = (props) => {
    const { data } = props ?? {};

    return goodsCategoryCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type GoodsCategoryCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof goodsCategoryCreate>>
>;
export type GoodsCategoryCreateMutationBody = GoodsCategorySaveRequest;
export type GoodsCategoryCreateMutationError = unknown;

/**
 * @summary 카테고리 등록
 */
export const useGoodsCategoryCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof goodsCategoryCreate>>,
      TError,
      { data: GoodsCategorySaveRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof goodsCategoryCreate>>,
  TError,
  { data: GoodsCategorySaveRequest },
  TContext
> => {
  const mutationOptions = getGoodsCategoryCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 전체 카테고리를 부모/깊이 정보가 담긴 평탄 목록으로 반환(3단 트리 구성용).
 * @summary 카테고리 목록
 */
export const goodsCategoryList = (signal?: AbortSignal) => {
  return customInstance<ResultDTOListGoodsCategoryNodeDto>({
    url: `/v1/goods-category/list`,
    method: "POST",
    signal,
  });
};

export const getGoodsCategoryListMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof goodsCategoryList>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof goodsCategoryList>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["goodsCategoryList"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof goodsCategoryList>>,
    void
  > = () => {
    return goodsCategoryList();
  };

  return { mutationFn, ...mutationOptions };
};

export type GoodsCategoryListMutationResult = NonNullable<
  Awaited<ReturnType<typeof goodsCategoryList>>
>;

export type GoodsCategoryListMutationError = unknown;

/**
 * @summary 카테고리 목록
 */
export const useGoodsCategoryList = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof goodsCategoryList>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof goodsCategoryList>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getGoodsCategoryListMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
