/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * GraceOn Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  IdListRequest,
  MemberSearchRequest,
  MemberUpdateRequest,
  ResultDTOInteger,
  ResultDTOMemberDetail,
  ResultDTOResInfinityListMemberListItem,
} from "../graceOnAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * @summary 회원 상세
 */
export const memberDetail = (id: number, signal?: AbortSignal) => {
  return customInstance<ResultDTOMemberDetail>({
    url: `/v1/member/${id}`,
    method: "GET",
    signal,
  });
};

export const getMemberDetailQueryKey = (id?: number) => {
  return [`/v1/member/${id}`] as const;
};

export const getMemberDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof memberDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof memberDetail>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getMemberDetailQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof memberDetail>>> = ({
    signal,
  }) => memberDetail(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof memberDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type MemberDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof memberDetail>>
>;
export type MemberDetailQueryError = unknown;

export function useMemberDetail<
  TData = Awaited<ReturnType<typeof memberDetail>>,
  TError = unknown
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof memberDetail>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof memberDetail>>,
          TError,
          Awaited<ReturnType<typeof memberDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMemberDetail<
  TData = Awaited<ReturnType<typeof memberDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof memberDetail>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof memberDetail>>,
          TError,
          Awaited<ReturnType<typeof memberDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMemberDetail<
  TData = Awaited<ReturnType<typeof memberDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof memberDetail>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 회원 상세
 */

export function useMemberDetail<
  TData = Awaited<ReturnType<typeof memberDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof memberDetail>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getMemberDetailQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 회원 수정
 */
export const memberUpdate = (
  id: number,
  memberUpdateRequest: MemberUpdateRequest
) => {
  return customInstance<ResultDTOMemberDetail>({
    url: `/v1/member/${id}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: memberUpdateRequest,
  });
};

export const getMemberUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof memberUpdate>>,
    TError,
    { id: number; data: MemberUpdateRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof memberUpdate>>,
  TError,
  { id: number; data: MemberUpdateRequest },
  TContext
> => {
  const mutationKey = ["memberUpdate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof memberUpdate>>,
    { id: number; data: MemberUpdateRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return memberUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type MemberUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof memberUpdate>>
>;
export type MemberUpdateMutationBody = MemberUpdateRequest;
export type MemberUpdateMutationError = unknown;

/**
 * @summary 회원 수정
 */
export const useMemberUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof memberUpdate>>,
      TError,
      { id: number; data: MemberUpdateRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof memberUpdate>>,
  TError,
  { id: number; data: MemberUpdateRequest },
  TContext
> => {
  const mutationOptions = getMemberUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 검색/필터/페이지네이션된 회원 목록을 반환한다.
 * @summary 회원 목록
 */
export const memberList = (
  memberSearchRequest: MemberSearchRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOResInfinityListMemberListItem>({
    url: `/v1/member/list`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: memberSearchRequest,
    signal,
  });
};

export const getMemberListMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof memberList>>,
    TError,
    { data: MemberSearchRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof memberList>>,
  TError,
  { data: MemberSearchRequest },
  TContext
> => {
  const mutationKey = ["memberList"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof memberList>>,
    { data: MemberSearchRequest }
  > = (props) => {
    const { data } = props ?? {};

    return memberList(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type MemberListMutationResult = NonNullable<
  Awaited<ReturnType<typeof memberList>>
>;
export type MemberListMutationBody = MemberSearchRequest;
export type MemberListMutationError = unknown;

/**
 * @summary 회원 목록
 */
export const useMemberList = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof memberList>>,
      TError,
      { data: MemberSearchRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof memberList>>,
  TError,
  { data: MemberSearchRequest },
  TContext
> => {
  const mutationOptions = getMemberListMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 선택한 회원을 INACTIVE로 변경한다.
 * @summary 회원 일괄 거부
 */
export const memberDeny = (
  idListRequest: IdListRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOInteger>({
    url: `/v1/member/deny`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: idListRequest,
    signal,
  });
};

export const getMemberDenyMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof memberDeny>>,
    TError,
    { data: IdListRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof memberDeny>>,
  TError,
  { data: IdListRequest },
  TContext
> => {
  const mutationKey = ["memberDeny"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof memberDeny>>,
    { data: IdListRequest }
  > = (props) => {
    const { data } = props ?? {};

    return memberDeny(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type MemberDenyMutationResult = NonNullable<
  Awaited<ReturnType<typeof memberDeny>>
>;
export type MemberDenyMutationBody = IdListRequest;
export type MemberDenyMutationError = unknown;

/**
 * @summary 회원 일괄 거부
 */
export const useMemberDeny = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof memberDeny>>,
      TError,
      { data: IdListRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof memberDeny>>,
  TError,
  { data: IdListRequest },
  TContext
> => {
  const mutationOptions = getMemberDenyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 선택한 회원을 CONFIRMED로 변경한다.
 * @summary 회원 일괄 승인
 */
export const memberApprove = (
  idListRequest: IdListRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOInteger>({
    url: `/v1/member/approve`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: idListRequest,
    signal,
  });
};

export const getMemberApproveMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof memberApprove>>,
    TError,
    { data: IdListRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof memberApprove>>,
  TError,
  { data: IdListRequest },
  TContext
> => {
  const mutationKey = ["memberApprove"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof memberApprove>>,
    { data: IdListRequest }
  > = (props) => {
    const { data } = props ?? {};

    return memberApprove(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type MemberApproveMutationResult = NonNullable<
  Awaited<ReturnType<typeof memberApprove>>
>;
export type MemberApproveMutationBody = IdListRequest;
export type MemberApproveMutationError = unknown;

/**
 * @summary 회원 일괄 승인
 */
export const useMemberApprove = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof memberApprove>>,
      TError,
      { data: IdListRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof memberApprove>>,
  TError,
  { data: IdListRequest },
  TContext
> => {
  const mutationOptions = getMemberApproveMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
