/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * GraceOn Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  MediaListParams,
  MediaUploadBody,
  MediaUploadParams,
  ResultDTOListString,
  ResultDTOMediaAssetDto,
  ResultDTOResInfinityListMediaAssetDto,
  ResultDTOVoid,
} from "../graceOnAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * 파일을 CDN에 업로드하고 자산으로 기록한 뒤 key/url을 반환한다.
 * @summary 미디어 업로드
 */
export const mediaUpload = (
  mediaUploadBody: MediaUploadBody,
  params?: MediaUploadParams,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOMediaAssetDto>({
    url: `/v1/media/upload`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: mediaUploadBody,
    params,
    signal,
  });
};

export const getMediaUploadMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof mediaUpload>>,
    TError,
    { data: MediaUploadBody; params?: MediaUploadParams },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof mediaUpload>>,
  TError,
  { data: MediaUploadBody; params?: MediaUploadParams },
  TContext
> => {
  const mutationKey = ["mediaUpload"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof mediaUpload>>,
    { data: MediaUploadBody; params?: MediaUploadParams }
  > = (props) => {
    const { data, params } = props ?? {};

    return mediaUpload(data, params);
  };

  return { mutationFn, ...mutationOptions };
};

export type MediaUploadMutationResult = NonNullable<
  Awaited<ReturnType<typeof mediaUpload>>
>;
export type MediaUploadMutationBody = MediaUploadBody;
export type MediaUploadMutationError = unknown;

/**
 * @summary 미디어 업로드
 */
export const useMediaUpload = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof mediaUpload>>,
      TError,
      { data: MediaUploadBody; params?: MediaUploadParams },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof mediaUpload>>,
  TError,
  { data: MediaUploadBody; params?: MediaUploadParams },
  TContext
> => {
  const mutationOptions = getMediaUploadMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 카테고리/파일명 검색 + 페이지네이션된 업로드 이미지 목록.
 * @summary 미디어 목록
 */
export const mediaList = (params?: MediaListParams, signal?: AbortSignal) => {
  return customInstance<ResultDTOResInfinityListMediaAssetDto>({
    url: `/v1/media`,
    method: "GET",
    params,
    signal,
  });
};

export const getMediaListQueryKey = (params?: MediaListParams) => {
  return [`/v1/media`, ...(params ? [params] : [])] as const;
};

export const getMediaListQueryOptions = <
  TData = Awaited<ReturnType<typeof mediaList>>,
  TError = unknown
>(
  params?: MediaListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof mediaList>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getMediaListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof mediaList>>> = ({
    signal,
  }) => mediaList(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof mediaList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type MediaListQueryResult = NonNullable<
  Awaited<ReturnType<typeof mediaList>>
>;
export type MediaListQueryError = unknown;

export function useMediaList<
  TData = Awaited<ReturnType<typeof mediaList>>,
  TError = unknown
>(
  params: undefined | MediaListParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof mediaList>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof mediaList>>,
          TError,
          Awaited<ReturnType<typeof mediaList>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMediaList<
  TData = Awaited<ReturnType<typeof mediaList>>,
  TError = unknown
>(
  params?: MediaListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof mediaList>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof mediaList>>,
          TError,
          Awaited<ReturnType<typeof mediaList>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMediaList<
  TData = Awaited<ReturnType<typeof mediaList>>,
  TError = unknown
>(
  params?: MediaListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof mediaList>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 미디어 목록
 */

export function useMediaList<
  TData = Awaited<ReturnType<typeof mediaList>>,
  TError = unknown
>(
  params?: MediaListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof mediaList>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getMediaListQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 라이브러리 필터용 카테고리 목록.
 * @summary 미디어 카테고리
 */
export const mediaCategories = (signal?: AbortSignal) => {
  return customInstance<ResultDTOListString>({
    url: `/v1/media/categories`,
    method: "GET",
    signal,
  });
};

export const getMediaCategoriesQueryKey = () => {
  return [`/v1/media/categories`] as const;
};

export const getMediaCategoriesQueryOptions = <
  TData = Awaited<ReturnType<typeof mediaCategories>>,
  TError = unknown
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof mediaCategories>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getMediaCategoriesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof mediaCategories>>> = ({
    signal,
  }) => mediaCategories(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof mediaCategories>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type MediaCategoriesQueryResult = NonNullable<
  Awaited<ReturnType<typeof mediaCategories>>
>;
export type MediaCategoriesQueryError = unknown;

export function useMediaCategories<
  TData = Awaited<ReturnType<typeof mediaCategories>>,
  TError = unknown
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof mediaCategories>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof mediaCategories>>,
          TError,
          Awaited<ReturnType<typeof mediaCategories>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMediaCategories<
  TData = Awaited<ReturnType<typeof mediaCategories>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof mediaCategories>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof mediaCategories>>,
          TError,
          Awaited<ReturnType<typeof mediaCategories>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMediaCategories<
  TData = Awaited<ReturnType<typeof mediaCategories>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof mediaCategories>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 미디어 카테고리
 */

export function useMediaCategories<
  TData = Awaited<ReturnType<typeof mediaCategories>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof mediaCategories>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getMediaCategoriesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 자산 기록과 저장된 객체를 삭제한다.
 * @summary 미디어 삭제
 */
export const mediaDelete = (id: number) => {
  return customInstance<ResultDTOVoid>({
    url: `/v1/media/${id}`,
    method: "DELETE",
  });
};

export const getMediaDeleteMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof mediaDelete>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof mediaDelete>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["mediaDelete"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof mediaDelete>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return mediaDelete(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type MediaDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof mediaDelete>>
>;

export type MediaDeleteMutationError = unknown;

/**
 * @summary 미디어 삭제
 */
export const useMediaDelete = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof mediaDelete>>,
      TError,
      { id: number },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof mediaDelete>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getMediaDeleteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
